### ISSUE TITLE
Setup Issue & PR template files

### ISSUE THREAD

**Issue by dej611** [italia/design-react-kit#10]
Create some template files to help contributors when documenting Issues or Pull Requests

**Comment by lazycipher** [comment]
Hey, @francescozaia  Can I work on this?

**Comment by francescozaia** [comment]
Of course @lazycipher, the repo is open to contributions. Thanks!

**Comment by lazycipher** [comment]
Hey, @francescozaia I've created a PR for this issue. Please review that and let me know the changes required!
