### ISSUE TITLE
[BUG] Could not find a declaration file for module 'react-transition-group/Transition'

### ISSUE THREAD

**Issue by Virtute90** [italia/design-react-kit#1012]
**Describe the bug**
I'm building my project but I encounter this problem:

```
node_modules/design-react-kit/dist/types/Accordion/AccordionBody.d.ts:2:33 - error TS7016: Could not find a declaration file for module 'react-transition-group/Transition'. '/var/www/html/node_modules/react-transition-group/cjs/Transition.js' implicitly has an 'any' type.

2 import { TransitionProps } from 'react-transition-group/Transition';
                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in node_modules/design-react-kit/dist/types/Accordion/AccordionBody.d.ts:2
```

**To Reproduce**

npm run build

**Solution**
The problem is solved by installing in my project `@types/react-transition-group`

**Other Required Information (please complete the following information):**

- OS: ubuntu 22.04
- Version 5.0.0-8

**Comment by astagi** [comment]
uhm should it be included in `dependencies` instead of `devDependencies`? @sabato-galasso
