### ISSUE TITLE
[FEATURE] Implement NavBar progress bar

### ISSUE THREAD

**Issue by astagi** [italia/design-react-kit#1015]
Implement progress bar in NavBar component. [Documentation](https://italia.github.io/bootstrap-italia/docs/menu-di-navigazione/navscroll/#progress-bar)

**Comment by vr1Ravi** [comment]
@astagi  can you elaborate more about this issue

**Comment by astagi** [comment]
@vr1Ravi thank you for your interest. The idea is to create a NavBar component following the vanilla JavaScript implementation of Bootstrap Italia https://italia.github.io/bootstrap-italia/docs/menu-di-navigazione/navscroll/#progress-bar .
