### ISSUE TITLE
[BUG]Typo  in README of branch `next`

### ISSUE THREAD

**Issue by RMCoder198** [italia/design-react-kit#102]
**Describe the bug**
There are typo's in README.me and README.EN.me

**To Reproduce**

1. Read and follow README
For example to run development server `yarn storybook:serve` needs to enter in command line but README.me suggest `yarn storybook-serve`
**Expected behavior**
There should not be any typo in README

**Other Required Information (please complete the following information):**
 - OS: [ubuntnu]
 - Browser [chrome]

**Comment by RMCoder198** [comment]
#99

**Comment by sanyamdogra** [comment]
Copy of #99
