### ISSUE TITLE
LinkListItem does not pass on "to"

### ISSUE THREAD

**Issue by ewedlund** [italia/design-react-kit#1033]
Passing a "to" prop to a LinkListItem in 5.0.0 does not work, it is being consumed and not passed on to the Tag component.

https://github.com/italia/design-react-kit/blob/2acd92f76fceae1f877d93099cabfb97fed92b98/src/LinkList/LinkListItem.tsx#L47

**Comment by astagi** [comment]
Thank you @ewedlund we'll investigate and solve the problem asap.

**Comment by Nick87** [comment]
What's the difference between `to` and `href` in this component? And how are they supposed to work together?

**Comment by ewedlund** [comment]
> What's the difference between `to` and `href` in this component? And how are they supposed to work together?

`to` is used with a [react router](https://reactrouter.com/) [Link](https://reactrouter.com/en/main/components/link#link), in order to do client side routing. If you use `href` instead, you would reload the page. You would not use them together. Something like this (at least this is what I have understood):

```
import { LinkList, LinkListItem } from "design-react-kit";
import { Link } from "react-router-dom";

<LinkList>
    <LinkListItem tag={Link} to="/home">
        <span>Home</span>
    </LinkListItem>
</LinkList>
```

I think this component should just ignore the `to` so that it is passed on to the `Tag` element through `attributes`, but right now it is being assigned to a variable, instead of leaving it in `attributes`.

**Comment by Nick87** [comment]
So we are assuming that, if the user passes the `to` prop, then the LinkListItem `tag` is a `react-router-dom` Link element that accepts a `to` prop?
React Router is not the only routing library that a user can use, this way, are not we coupling a general element (the prop `tag`) to a specific attribute (`to`) that we are assuming the element accepts?

**Comment by ewedlund** [comment]
> So we are assuming that, if the user passes the `to` prop, then the LinkListItem `tag` is a `react-router-dom` Link element that accepts a `to` prop? React Router is not the only routing library that a user can use, this way, are not we coupling a general element (the prop `tag`) to a specific attribute (`to`) that we are assuming the element accepts?

I think the `to` prop should not be declared at all in the LinkListItem component, as it would be an attribute that is transparently passed on to the component in `tag`. If you use a routing library that uses the prop `myrouteprop`, that prop would be passed on in the same way (that would work even now). 

The problem is that currently `to` is neither being passed on, nor is it being handled in any way. But maybe I am missing something?

**Comment by Nick87** [comment]
I don't think that the `tag` can accept any React Element, it's an ElementType, so it can be something like `h1`, `header`, `p`, not a react router Link element nor any other element.
I think that, if we want to allow managed client side redirect without a full page refresh, the whole `LinkListItem` must be refactored, it is not just a matter of passing a prop.

And by the way, you cannot pass a `react-router-dom` Link element to the prop `tag`:

![image](https://github.com/italia/design-react-kit/assets/1497044/c9fe5a59-59db-4bba-a129-6e44a0672555)

**Comment by ewedlund** [comment]
> I don't think that the `tag` can accept any React Element, it's an ElementType, so it can be something like `h1`, `p`, not a react router Link element nor any other element. I think that, if we want to allow managed client side redirect without a full page refresh, the whole `LinkListItem` must be refactored, it is not just a matter of passing a prop.

AFAIK you can pass a component to an ElementType, I have tested and it does work.

> 
> And by the way, you cannot pass a `react-router-dom` Link element to the prop `tag`:
> 
> ![image](https://private-user-images.githubusercontent.com/1497044/315240062-c9fe5a59-59db-4bba-a129-6e44a0672555.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMTUzNjIsIm5iZiI6MTcxMTAxNTA2MiwicGF0aCI6Ii8xNDk3MDQ0LzMxNTI0MDA2Mi1jOWZlNWE1OS01OWRiLTRiYmEtYTEyOS02ZTQ0YTA2NzI1NTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjFUMDk1NzQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzQ3NGEzMTkxYjA2YWZjNTY2OTlkZTI3MWI0ZjI4ZGQzMzVmZTFjNjcyNWI1ZDY5NDhlYjI1MDBmZTAyMDhhOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.rsJqIMNjedvG94mSZ_COKGhKW7I1BphRqGBVx2UXEiQ)

You are passing an instance of the component, try doing

```
<LinkListItem tag={Link} to='myRoute'>
```

**Comment by ewedlund** [comment]
> You are correct, it does work this way, but in this case the `to` prop is no longer transparent as you said it should be (and I agree), and you are assuming that `Link` accepts a `to` prop, but that might not be necessarily the case as I am not assuming that `Link` is a `react-router-dom` type of element.

Well, I **do** know the type of `Link` since I am the one passing it to the `tag` prop. I understand what you are saying about the `to` prop though, that there might be another routing framework that uses another prop. React router is however very widespread, so it  would be a very common case, and from the [documentation](https://github.com/italia/design-react-kit/blob/2acd92f76fceae1f877d93099cabfb97fed92b98/src/LinkList/LinkListItem.tsx#L27C1-L28C1) I would suspect that it was the reason why the `to` prop was being passed in the first place.

An alternative would be to permit passing generic extra props that would be passed to the tag (I suppose that is what the variable `attributes` is for?).

**Comment by astagi** [comment]
Thanks @ewedlund would you mind send a PR to solve this problem? We’ll merge it in the next version along other fixes.

**Comment by astagi** [comment]
Thanks @ewedlund .. @Nick87 which kind of refactoring are you thinking about? 

For now we can remove 'to' property to avoid confusion.. it would be great to integrate an example with Link in documentation, I don't know if @ewedlund want/has time to add it.

**Comment by Nick87** [comment]
I made a few tests, and passing the `to` prop down to the `Tag` element like this:

![image](https://github.com/italia/design-react-kit/assets/1497044/60e4e5c1-2647-48e9-ab65-2c806838872f)

does not do the job, since the generated html is:

![image](https://github.com/italia/design-react-kit/assets/1497044/97350fc6-ce03-4ab5-b114-42dce34f4246)

We get the `to` attribute with the anchor tag, which does not work.
For comparison, a classic `<NavLink to="/login">LOGIN</Login>` generates this html:

![image](https://github.com/italia/design-react-kit/assets/1497044/e3c881e1-73be-45da-ab97-dfbc5113f0be)

I guess that `to` is completely useless here and we can have the current `href` prop from `LinkListItem` work with `react-router-dom` as well.

This code:

![image](https://github.com/italia/design-react-kit/assets/1497044/8feea7ee-2ccc-4b32-a1f6-ebe43e4bb787)

with this route configuration:

![image](https://github.com/italia/design-react-kit/assets/1497044/24beb806-753b-42d5-a879-335aecc72e9a)

redirects the user to the Login page, as expected.

**Comment by astagi** [comment]
Thank you for testing it out @Nick87 

Do you agree with @ewedlund removing 'to' property as suggested by the PR and using only href with a proper routing configuration?

**Comment by ewedlund** [comment]
> I made a few tests, and passing the `to` prop down to the `Tag` element like this:
> 
> ![image](https://private-user-images.githubusercontent.com/1497044/316675109-60e4e5c1-2647-48e9-ab65-2c806838872f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0MzY2MzYsIm5iZiI6MTcxMTQzNjMzNiwicGF0aCI6Ii8xNDk3MDQ0LzMxNjY3NTEwOS02MGU0ZTVjMS0yNjQ3LTQ4ZTktYWI2NS0yYzgwNjgzODg3MmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjZUMDY1ODU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDVhM2M0OGEyMjU2MDQ4NDUzNGM4MjcyYjc0MjQzNGE0NGE0NjY4NDcyOWJiOWYxZTgwNGQyOWQ1NjY0YjQxZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.5dJGrAgNh6V-cyuvGU9Uy2AwOgmPORV4hW4ISojOWuU)

So it seems that in this example you are using `<LinkListItem />` without passing `tag = {Link}`, so it defaults to `tag = 'a'`, which is a regular `html` element that does not recognize the `to` prop. In this case you simply should not use the `to` prop and just pass `href`.

> 
> I guess that `to` is completely useless here and we can have the current `href` prop from `LinkListItem` work with `react-router-dom` as well.

No, it is not useless: a `Link` does not have the `href` prop, and using a regular anchor will result in the page being reloaded instead of using client side routing. The fact that you see an anchor in the resulting `html` does not mean that it is the same thing.

**Comment by ewedlund** [comment]
> Thank you for testing it out @Nick87
> 
> Do you agree with @ewedlund removing 'to' property as suggested by the PR and using only href with a proper routing configuration?

Actually in the PR I only suggested to remove the **assignment** of the variable `to` in order to pass the `to` prop on to the `Tag` element via `attributes`., not to remove the prop. This is surely not the best approach because it will not cover all cases, but at least it allows for the  simplest routing cases. 

I agree with @Nick87 that it would need some more work to make a more complete solution, either by allowing to pass any extra props that are passed on via `attributes`, or passing an element. In any way it would need some work to analyze the various use cases.

**Comment by Nick87** [comment]
> Thank you for testing it out @Nick87
> 
> Do you agree with @ewedlund removing 'to' property as suggested by the PR and using only href with a proper routing configuration?

That's not what @ewedlund has suggested, and after @ewedlund 's comments, I need to take a closer look to check that what I thought is correct.

**Comment by astagi** [comment]
Sorry @Nick87 @ewedlund I'm on holidays atm I can only interact with my phone, not the best to look at the code :) anyway I understood the problem and the solution using 'to' along attributes.. if this problem is blocking I can accept @ewedlund solution and release a new patch version, then we can reopen the issue and continue the discussion (and possible refactoring/enhancements).. let me know

**Comment by Nick87** [comment]
> Sorry @Nick87 @ewedlund I'm on holidays atm I can only interact with my phone, not the best to look at the code :) anyway I understood the problem and the solution using 'to' along attributes.. if this problem is blocking I can accept @ewedlund solution and release a new patch version, then we can reopen the issue and continue the discussion (and possible refactoring/enhancements).. let me know

I don't think this is a blocker, the `to` prop is just there for no reason and completely useless at the moment, so @ewedlund's PR, which removes it, is definitely good :)

**Comment by Nick87** [comment]
@ewedlund is definitely and what I suggested earlier definitely does not work since it causes a full page reload, but I may be on to  something that seems to be working.

With the `to` prop out of the game, we can add a prop tagProps, defined as:

`tagProps?: Record<string, any>`

containing all the props that we want to pass to the `Tag` component, which which defaults to an empty object.

![image](https://github.com/italia/design-react-kit/assets/1497044/b3c90c7e-1807-4583-875a-8ef4e745bec0)

This way we can use any object as `tag` and pass it all the props we want, like this:

![image](https://github.com/italia/design-react-kit/assets/1497044/578a5608-5606-4e81-a9e2-71c6f66be43d)

and the code above redirects the user to the correct route without triggering a full page refresh

**Comment by ewedlund** [comment]
> > Sorry @Nick87 @ewedlund I'm on holidays atm I can only interact with my phone, not the best to look at the code :) anyway I understood the problem and the solution using 'to' along attributes.. if this problem is blocking I can accept @ewedlund solution and release a new patch version, then we can reopen the issue and continue the discussion (and possible refactoring/enhancements).. let me know
> 
> I don't think this is a blocker, the `to` prop is just there for no reason and completely useless at the moment, so @ewedlund's PR, which removes it, is definitely good :)

No, my PR does **not** remove it, it just deletes the line that blocked it from being passed on to the `tag` element. It is a quick fix, so if you opt for another solution it's OK with me. It is not blocking, just annoying having to make a workaround in my code.

**Comment by ewedlund** [comment]
> @ewedlund is definitely right and what I suggested earlier does not work since it causes a full page refresh, but I may be on to something that seems to be working.
> 
> With the `to` prop out of the game, we could use a prop `tagProps`, defined as:
> 
> `tagProps?: Record<string, any>`
> 
> containing all the props that we want to pass to the `Tag` component, which which defaults to an empty object.
> 
> ![image](https://private-user-images.githubusercontent.com/1497044/317048367-b3c90c7e-1807-4583-875a-8ef4e745bec0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MjM1MzMsIm5iZiI6MTcxMTUyMzIzMywicGF0aCI6Ii8xNDk3MDQ0LzMxNzA0ODM2Ny1iM2M5MGM3ZS0xODA3LTQ1ODMtODc1YS04ZWY0ZTc0NWJlYzAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjdUMDcwNzEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzM5NWE5NjBjNTNlYzg1MWUwY2Q4NjhiYTRjODJlM2E1ODI3NTZlNDRkY2NlYWRmYjQ0MGUzYTU2NmE0M2U3ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.B84d2Y0tPXPTLyWB6DbWC_h89ghHro5zXdu3dElDN6Q)
> 
> This way we can use any object as `tag` and pass it all the props we want, like this:
> 
> ![image](https://private-user-images.githubusercontent.com/1497044/317048935-578a5608-5606-4e81-a9e2-71c6f66be43d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MjM1MzMsIm5iZiI6MTcxMTUyMzIzMywicGF0aCI6Ii8xNDk3MDQ0LzMxNzA0ODkzNS01NzhhNTYwOC01NjA2LTRlODEtYTllMi03MWM2ZjY2YmU0M2QucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjdUMDcwNzEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTQ3ZDFjNzcxMmFkN2VkZDVmZmE3ZmQxYTNjZDhlMDUyMDk3ZDNkOWRlYWJmNzMzZmU0MWY2MjEyZDUyNjE3NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.kfmyEzqNHbaDQDF74RTl9vJOacMNmXVylWmo-MiGp_M)
> 
> and the code above redirects the user to the correct route without triggering a full page refresh

This was one of my proposals and fine with me. I am not sure what your approach is on other components, but in my opinion it might be a good idea to make sure that they are similar (if there are other cases like this).

 E.g. in the [Select](https://github.com/italia/design-react-kit/blob/main/src/Select/Select.tsx) component, it is only possibile to pass `onChange` and `disabled`, but I need to be able to pass `required` and `value` (and `multiple` but that does not seem to work in terms of visualization). It is not exactly the same case, but maybe using the same approach and name for the props to pass on could be useful?

**Comment by Nick87** [comment]
I don't think we can use with `LinkListItem` the same approach as `Select`, since here we are trying to add a prop that does not correspond to a standard html attribute. For this reason I guess the only approach is to explicitly add it.

I have taken a look to the `Select` element, and I found some problems that maybe I'll describe in a dedicated issue.

**Comment by Nick87** [comment]
> but I need to be able to pass `required` and `value` (and `multiple` but that does not seem to work in terms of visualization)

@ewedlund take a look at #1042, maybe that fixes your problem

**Comment by astagi** [comment]
Good catch @Nick87! @ewedlund is @Nick87 approach right for you?

**Comment by ewedlund** [comment]
> Good catch @Nick87! @ewedlund is @Nick87 approach right for you?

Not sure which one you mean but yes I think we have sorted things out, thank you to both of you!

I will close my PR since @Nick87 is taking care of it.

**Comment by Nick87** [comment]
@astagi  @ewedlund do you mean that the `tagProps` approach is fine for you and that I should open a PR with that?

**Comment by Nick87** [comment]
You're right, my approach is not used elsewhere, and I think that your pr, #1039, is the right way of solving the issue: by removing the `to` prop there, it is included in `attributes` hence making sure it is passed on to the `tag` component.
Sorry that I am figuring out only now what you were trying to accomplish.

**Comment by Nick87** [comment]
> (BTW I just realized that `BottomNavItem` needs fixing to!)

with the `className` attribute that is simply ignored?

**Comment by ewedlund** [comment]
> > (BTW I just realized that `BottomNavItem` needs fixing to!)
> 
> what problem do you see there?

I haven't tested it, but it does not accept a `to` prop so it is the same problem when using it with a `react-router` `Link`. I can create an issue when I have time to try it out.

**Comment by Nick87** [comment]
@ewedlund `BottomNavItem`, unlike `LinkListItem`, does NOT spread the `attributes` prop to the `Tag` element: for this reason, I do not think that adding the `to` will solve the problem. I guess a different approach over there,

**Comment by astagi** [comment]
@Nick87 I merged @ewedlund PR if you want to open a new issue to fix that problem on the other components feel free to do it!

**Comment by ewedlund** [comment]
> @Nick87 I merged @ewedlund PR if you want to open a new issue to fix that problem on the other components feel free to do it!

Great, thank you!
