### ISSUE TITLE
[BUG] Typescript compilation error on Accordion component

### ISSUE THREAD

**Issue by roffus** [italia/design-react-kit#1034]
I'm using react typescript and after updating the library to version 5.0.0 a compilation problem arose with the Accordion component.

The error is the following:
`TS2559: Type { children: Element; } has no properties in common with type IntrinsicAttributes & AccordionProps`
and appear on `<Accordion>`, `<AccordionItem>`, `<AccordionHeader>`

e.g.
```js
              <Accordion>
                <AccordionItem>
                  <AccordionHeader>Header</AccordionHeader>
                </AccordionItem>
              </Accordion>

```

compilerOptions

```json
{
  "compilerOptions": {
    "target": "ESNext",
    "useDefineForClassFields": true,
    "lib": ["ES2020", "DOM", "DOM.Iterable"],
    "module": "ESNext",
    "skipLibCheck": true,

    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",
  },
  "include": ["src"],
}
```

**Comment by Virtute90** [comment]
I have entered a PR for the resolution of this problem
