### ISSUE TITLE
Select not calling onChange

### ISSUE THREAD

**Issue by ewedlund** [italia/design-react-kit#1035]
If you pass a function in the onChange prop, it will not be called. I think the Select component is passing the wrong prop to the underlying `<select>` component in 

https://github.com/italia/design-react-kit/blob/2acd92f76fceae1f877d93099cabfb97fed92b98/src/Select/Select.tsx#L31C5-L31C17

I think 
```
  const inputProps = {
    disabled: disabled,
    handleChange: handleChange
  };
```
should be
```
  const inputProps = {
    disabled: disabled,
    onChange: handleChange
  };
```

(at least this worked for me)

**Comment by astagi** [comment]
Thanks @Virtute90 for having solved this problem!
