### ISSUE TITLE
[BUG] Infinite re-renders when using useNavScroll

### ISSUE THREAD

**Issue by pantpad** [italia/design-react-kit#1057]
**Describe the bug**
Using the useNavScroll hook and its register function triggers an infinite re-rendering of the component.

**To Reproduce**

1. Install the dependencies as described in the italia/design-react-kit
2. Go to (https://italia.github.io/design-react-kit/?path=/docs/documentazione-menu-di-navigazione-navscroll--documentazione)
3. Copy and paste first example inside your own component. 
4. Add console.log to check amount of re-renders.
5. Run the app and check the waterfall of logs that keeps appearing as soon as the component loads (i'm not scrolling down or up)

**Expected behavior**
The useNavScroll seems to work as intended, it simply creates an infinite re-render of the page.

**Screenshots**
![Screenshot 2023-06-12 165102](https://github.com/italia/design-react-kit/assets/138708449/c0ad76ff-c6f7-4401-ae7c-7251c334849c)

**Comment by Virtute90** [comment]
A new render is performed every time the page is "scrolled", this is how the component works.

At each renderer the references of where you have arrived are updated and the navigation menu is updated.

**Comment by pantpad** [comment]
> A new render is performed every time the page is "scrolled", this is how the component works.
> 
> At each renderer the references of where you have arrived are updated and the navigation menu is updated.

The problem is that even if I don't scroll or interact with the page in any way, re-renderings keep happening.
In a couple of seconds I get almost 1000 re-renders.

Is this supposed to happen as well?

**Comment by Nick87** [comment]
I was able  to reproduce and hopefully fix the issue that @pantpad reported: please take a look at #1061.

**Comment by astagi** [comment]
@Nick87 thank you so much! @pantpad a new version (5.0.4) is now available on NPM with #1061 included! let us know if everything runs fine now!
