### ISSUE TITLE
[BUG] Dimmer overlay and mobile alignment

### ISSUE THREAD

**Issue by zetareticoli** [italia/design-react-kit#1063]
**Describe the bug**

### Overlay Bug
The dimmer overlay doesn't work as intended. His content appears below page.

See example:
![Screenshot 2024-05-09 alle 11 50 14](https://github.com/italia/design-react-kit/assets/69706/acbc03cd-9ae8-44bc-a4c8-52cf9971e41f)

This bug appears in one variant only, the one with three cards.

### Alignment bug
On mobile devices, the dimmer cards and content disappears, see example:
![Screenshot 2024-05-09 alle 11 50 22](https://github.com/italia/design-react-kit/assets/69706/acb5b2d5-fc16-4b74-9d40-3976be1ca5d1)

**Other Required Information (please complete the following information):**
- OS: Mac OS Sonoma 14.1
- Browser: Safari 17.1

**Comment by astagi** [comment]
Fixed in https://github.com/italia/design-react-kit/commit/315760a217541f9a5b73dc9ea92b8c559f4be362 thanks @zetareticoli
