### ISSUE TITLE
Fix: remove defaultProps on Alert

### ISSUE THREAD

**Issue by Virtute90** [italia/design-react-kit#1067]
Nel componente Alert viene usato la proprietà defaultProps che è stata deprecata: [Warn when Using DefaultProps on Function Components ](https://github.com/facebook/react/pull/16210)

![image](https://github.com/italia/design-react-kit/assets/32056724/13f78a77-e0db-4a09-bb32-cbfc713ae76e)

La modifica si potrebbe aggiungere all'aggiornamento a React 18: #963 #1049 

https://github.com/italia/design-react-kit/blob/1074d49d184ac8bd8fb8de8c5b79e0b049c5e24e/src/Alert/Alert.tsx#L35

**Comment by astagi** [comment]
@Virtute90 su questa potresti mandare una PR? riparti pure anche da main poi mergio insieme all'aggiornamento alla 18 oppure fai sul branch dell'aggiornamento.. Grazie 🙏
