### ISSUE TITLE
Select Component and Label Overlaps in Select Tab

### ISSUE THREAD

**Issue by Diuda** [italia/design-react-kit#107]
**Describe the bug**
The Select Component and Label overlaps in Select Tab. Branch: `next`

**To Reproduce**
1. Go to Select Component
2. Label and Select Container overlaps

**Expected behavior**
Label should be in next line after the Select Conatiner

**Screenshots**

**Current State**
![Screenshot from 2019-03-16 17-08-19](https://user-images.githubusercontent.com/12708871/54474842-0447c600-4810-11e9-92f5-d4f9ac2b0cbe.png)

**Expected State**
![Screenshot from 2019-03-16 17-08-35](https://user-images.githubusercontent.com/12708871/54474854-23deee80-4810-11e9-9042-cd309c48437b.png)

**Other Required Information (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Chrome
 - Version  73.0.3683.75

**Comment by sanyamdogra** [comment]
Hey @Diuda, will you like to give it a shot?

**Comment by Diuda** [comment]
Yeah sure
