### ISSUE TITLE
Componente `Bottomnav`: non funzionano gli esempi nella pagina di documentazione

### ISSUE THREAD

**Issue by Fupete** [italia/design-react-kit#1083]
## Cosa

Nella [pagina di documentazione storybook](https://italia.github.io/design-react-kit/?path=/docs/documentazione-menu-di-navigazione-bottomnav--documentazione) del componente non funzionano gli esempi, mostrano sempre una versione base tagliata sia come rendering che codice. Vedi immagine: 
![immagine](https://github.com/user-attachments/assets/a22eab97-6bdc-4573-98b0-3300b7ceadb9)

Gli esempi a sé invece ([es. con badge](https://italia.github.io/design-react-kit/?path=/story/documentazione-menu-di-navigazione-bottomnav--esempio-badge)) sembrano funzionare correttamente.

## Perché
Documentazione fuorviante. 

## Contesto
Verifiche di accessibilità sui componenti.

⚠️ Sarà da aggiornare lo status delle verifiche nella [board census ](https://github.com/orgs/italia/projects/32/views/1)alla risoluzione.

## Altro

**Comment by Virtute90** [comment]
Inserito fix per la documentazione
