### ISSUE TITLE
Verificare uso attributo `title="icon"` nelle svg

### ISSUE THREAD

**Issue by Fupete** [italia/design-react-kit#1084]
## Cosa

Verificare il perché della presenza di `title="icon"` dentro le icone svg. 
In alcuni componenti, ad esempio nei casi di Bottomnav e Toolbar, il lettore di schermo legge infatti quell'attributo title prima dei contenuti, cosa non corretta.  

Valutare come e se uniformare le icone svg con Bootstrap Italia. 

## Perché
Amichevole con i lettori di schermo. 

## Contesto
Verifiche di accessibilità sui componenti.

⚠️ Sarà da aggiornare lo status delle verifiche nella [board census ](https://github.com/orgs/italia/projects/32/views/1)alla risoluzione.

## Altro

**Comment by Fupete** [comment]
Secondo me sì, seguendo quanto già discusso qui https://github.com/italia/bootstrap-italia/issues/749#issuecomment-1293294166 con @cfabry e @astagi.

**Comment by Virtute90** [comment]
> Secondo me sì, seguendo quanto già discusso qui [italia/bootstrap-italia#749 (comment)](https://github.com/italia/bootstrap-italia/issues/749#issuecomment-1293294166) con @cfabry e @astagi.

Ok allora me ne occupo io!

**Comment by Virtute90** [comment]
Ho rimosso il valore di default per title lasciando la possibilità di inserire a piacimento il valore che si vuole.
In questa maniera non viene inserire il `<title></title>` di deafult,

**Comment by Fupete** [comment]
Perfect. I leave the final review to @astagi Thanks.

**Comment by Fupete** [comment]
Ottimo @astagi. Ho aggiornato io la board del component census risolvendo la 1083 e 1084.
