### ISSUE TITLE
Next and Previous Icons not appearing on Pager 

### ISSUE THREAD

**Issue by Diuda** [italia/design-react-kit#109]
**Describe the bug**
`PagerLink` Component not working for Previous and Next items in `Pager` Component.

**To Reproduce**
1. Go to Pager tab
2. Click on any sub tab 
3. The component exists but icons don't show up for _previous_ and _next_ list

**Expected behavior**
_Previous_ and _Next_ link should appear before/after the numbered paginated tabs

**Screenshots**
**Highlighted(focused) list without icons**
![Screenshot from 2019-03-16 20-38-56](https://user-images.githubusercontent.com/12708871/54477302-c4dba280-482c-11e9-9ddf-53b056593e63.png)

**Other Required Information (please complete the following information):**
 - OS: ubuntu 18.04
 - Browser: Chrome]
 - Version: 73.0.3683.75

**Comment by RMCoder198** [comment]
@Diuda  I have already created an issue for icons. Every component has this problem. You don't need to create a separate issue for this.

**Comment by RMCoder198** [comment]
#105 

You can close this issue now.

**Comment by Diuda** [comment]
I thought that was specific to a component. Nevermind, My bad. I'll close this now.
