### ISSUE TITLE
Componente `hero`: review a11y 

### ISSUE THREAD

**Issue by Fupete** [italia/design-react-kit#1092]
### Esiste già una discussione sul tema che ti interessa, o su un tema simile?

- [X] Ho verificato e non esiste

### Versione della libreria

5.2.0

### Cosa

Le varianti non sembrano seguire la struttura del componente in Bootstrap Italia. Probabilmente la presente struttura deriva da una precedente versione di Bootstrap Italia e c'è stata divergenza. 

In particolare:
- Il componente dovrebbe essere racchiuso dentro una `section`, e laddove necessario (varianti immagine) con`aria-label` dedicata. 
- Da verificare inoltre l'uso di `h2`al posto di `h1` negli esempi per miglior interpretazione della corretta gerarchia dei titoli. 
- C'è un bug nell'ultima variante con testo sovrapposto, all'immagine manca l'overlay di colore grigio scuro per garantire l'accessibilità del testo. 

### Perché

Coerenza tra le risorse di Design system .italia. Amichevole con i lettori di schermo. Visivamente accessibile.

### Contesto

Verifiche di accessibilità sui componenti.

⚠️ Sarà da aggiornare lo status delle verifiche nella [board census ](https://github.com/orgs/italia/projects/32/views/1)alla risoluzione.

### Altro

Si segnala la issue aperta anche su Bootstrap Italia https://github.com/italia/bootstrap-italia/issues/1175, specialmente in merito al deprecare la variante con testo sovrapposto e al ripensare lo `span` Categoria nelle varianti con testo. Da sincronizzare le soluzioni.

**Comment by Virtute90** [comment]
Inserita PR
