### ISSUE TITLE
Componente `modale`: h2 per i titoli, non h5 e link sbagliato a doc mdn

### ISSUE THREAD

**Issue by Fupete** [italia/design-react-kit#1093]
### Esiste già una discussione sul tema che ti interessa, o su un tema simile?

- [X] Ho verificato e non esiste

### Versione della libreria

5.2.0

### Cosa

Come in Bootstrap Italia e in Angular kit si consiglia di usare in tutte le varianti il tag `h2` per il titolo della modale, al posto dell'attuale di `h5`. Per rispettare la corretta gerarchia degli heading di pagina. 
Aggiungendo poi la classe`h5` per la corretta dimensione del testo. 

Si segnala inoltre che uno dei link MDN in apertura porta a una pagina 404. 

### Perché

Navigabile. Documentazione comprensibile.

### Contesto

Verifiche di accessibilità sui componenti.

⚠️ Sarà da aggiornare lo status delle verifiche nella [board census ](https://github.com/orgs/italia/projects/32/views/1)alla risoluzione.

### Altro

Ci sarà un'altra cosa da sincronizzare nella variante con icona, dopo la risoluzione di questa su Bootstrap Italia: https://github.com/italia/bootstrap-italia/issues/1176

**Comment by Virtute90** [comment]
Inserita PR
