### ISSUE TITLE
Componente `Toolbar`: Criticità di accessibilità relative al layout

### ISSUE THREAD

**Issue by Mattia541993** [italia/design-react-kit#1097]
### Esiste già una discussione sul tema che ti interessa, o su un tema simile?

- [X] Ho verificato e non esiste

### Versione della libreria

5.2.0

### Cosa

- Nell'esempio con icone grandi e nell'esempio con divisori, lo screen reader legge senza spazio "Preferitielemento disabilitato". L'assenza dello spazio tra "Preferiti" e "elemento" può creare confusione in particolare in chi usa il display Braille o nei casi in cui il nome del collegamento sia costituito da una sola lettera. In questo secondo caso il lettore di schermo leggerebbe, ad esempio "Eelemento disabilitato", "Helemento disabilitato" "Nelemento disabilitato".
Possibile soluzione: usare al posto di spazio "&nbsp;".
- I divisori definiti con  ToolbarItemDivider non vengono letti dal lettore di schermo (sono aria-hidden="true"). Nella versione Bootstrap i divisori vengono letti correttamente.

### Perché

Per omogeneità tra i vari framework considerati da Designers Italia e per chiarezza nel rendere esplicita la semantica dei divisori in React

### Altro

Riporto l'[issue originale](https://github.com/italia/bootstrap-italia/issues/1192) pubblicata nel repository di Bootstrap Italia in quanto riguarda entrambi i framework

**Comment by Fupete** [comment]
Vedi https://github.com/italia/bootstrap-italia/issues/1192#issuecomment-2325099192
