### ISSUE TITLE
Componente `Rating`: Operabilità da tastiera

### ISSUE THREAD

**Issue by Mattia541993** [italia/design-react-kit#1098]
### Esiste già una discussione sul tema che ti interessa, o su un tema simile?

- [X] Ho verificato e non esiste

### Versione della libreria

5.2.0

### Cosa

Tramite tastiera o screen reader non è possibile attivare o disattivare le "stelline". Sebbene attraverso lo screen reader vengano letti i valori delle "stelline" ("Valuta 4 su 5"), non è possibile selezionarli da tastiera.

### Perché

In riferimento alle [WCAG 2.1](https://www.w3.org/TR/WCAG21/#keyboard)

**Comment by astagi** [comment]
Grazie @Mattia541993 fixato qua https://github.com/italia/design-react-kit/commit/bd9ddbabc1a997ba8fdd08461172cd6a860623b2
