### ISSUE TITLE
Componente `Radio Button`: cosa si intende per gruppo?

### ISSUE THREAD

**Issue by Mattia541993** [italia/design-react-kit#1100]
### Esiste già una discussione sul tema che ti interessa, o su un tema simile?

- [X] Ho verificato e non esiste

### Versione della libreria

2.9.0

### Cosa

Nella sezione [Gruppi](https://italia.github.io/bootstrap-italia/docs/form/radio-button/#gruppi) i due gruppi di radio button sono distinguibili solo visivamente. Per permettere alle tecnologie assistive di determinare programmaticamente l'esistenza di un gruppo è necessario ragguppare gli elementi `<input type="radio">` in un `<fieldset>`. Gli elementi `<input type="radio">` con lo stesso valore dell'attributo `name` non vengono riconosciuti dalle tecnologie assistive come appartenenti allo stesso gruppo: questo attributo infatti serve allo user agent per garantire che `input type="radio"` con lo stesso `name` non possano essere selezionati contemporaneamente, rendendoli quindi mutuamente esclusivi. 
Inoltre la semantica di "gruppo" può non essere legata alla mutua esclusività dei vari radio button: ci possono essere radio button mutuamente esclusivi anche in due gruppi di campi diversi, si pensi ad esempio al caso in cui ci sono due insiemi di campi per profilare un'azienda o una persona fisica e in ciascuno di questi un radio button con lo stesso `name` scritto in parti diverse della pagina. Anche per questo motivo è necessario utilizzare il `<fieldset>` per raggruppare gli elementi.

### Perché

In riferimento a [WCAG 1.3.1](https://www.w3.org/TR/WCAG21/#info-and-relationships)

**Comment by Fupete** [comment]
Ciao @Mattia541993, grazie per la segnalazione.

Il problema è noto, ed è presente anche nei checkbox a dirla tutta.
 
Qui la segnalazione originale in Bootstrap Italia: https://github.com/italia/bootstrap-italia/issues/1069). 
Un volta risolta in Bootstrap Italia sarà da correggere ovviamente anche in React in Angular Kit a cascata.

Lascio aperta per tracciare.
