### ISSUE TITLE
Componente `Avatar`: variante testo link sottolineati, e verifiche su esempi in documentazione. 

### ISSUE THREAD

**Issue by Fupete** [italia/design-react-kit#1123]
### Esiste già una discussione sul tema che ti interessa, o su un tema simile?

- [X] Ho verificato e non esiste

### Versione della libreria

Corrente

### Cosa

Come da oggetto: una volta risolto su Bootstrap Italia https://github.com/italia/bootstrap-italia/issues/1272, andrà implementato anche qui il fatto che i link delle varianti con testo devono essere sottolineati. Probabilmente il fix sarà solo lato `scss` quindi dovrebbe essere solo aggiornare Bootstrap Italia. 

Inoltre: nella documentazione gli esempi nella pagina di introduzione non sembrano corrispondere talvolta al titoletto di sezione (vedi esempi con testo aggiuntivo), controllare. 

### Perché

Visivamente accessibile. Documentazione stabile. 

### Contesto

Verifiche di accessibilità e coerenza. 

### Altro

Già risolta in UI Kit Italia qui: https://github.com/italia/design-ui-kit/issues/134

**Comment by astagi** [comment]
Confermo che questa issue verrà risolta con l'aggiornamento a bootstrap italia 12.x
