### ISSUE TITLE
Label in FormGroup should come back inside input field if the field is out of Focus being empty

### ISSUE THREAD

**Issue by Diuda** [italia/design-react-kit#114]
**Is your feature request related to a problem? Please describe.**
A feature where the `Label` in `FormGroup` should come back to the original place if the `Input` field becomes empty after typing and getting it out of focus. 
Currently, it gets `transformed` on typing and does not come back if the `Input` field becomes empty or goes out of focus being empty.

**Describe the solution you'd like**
We can remove the `active` class once the `Input` field becomes empty or goes out of focus while being empty. 
This 'active' class is added to the `Label` Component inside FormGroup once the typing starts in `Input` field and is never removed.

**Issue**
Look at the label on the second Input field. Should come back to it's original position
![Screenshot from 2019-03-17 01-56-34](https://user-images.githubusercontent.com/12708871/54481249-6a583b80-4858-11e9-80f2-1c3079455583.png)

**Additional context**
Idealy a class should be added and removed only if the `Input` field is empty and out of focus.

**Comment by sanyamdogra** [comment]
Solved in #255, closing it.
