### ISSUE TITLE
Label issue in Input Group Component

### ISSUE THREAD

**Issue by Diuda** [italia/design-react-kit#128]
**Describe the bug**
The URL `Label` overlaps with the input field of URL in `InputGroup` Component

**To Reproduce**
1. Go to `InputGroup` Component
2. Click on `Esempi`
3. See the label overlapping

**Expected behavior**
The label should be in the next line of the input field.

**Screenshots**
Current State
![Screenshot from 2019-03-20 00-52-27](https://user-images.githubusercontent.com/12708871/54635584-83f0c180-4aaa-11e9-9f6c-46c5561d1987.png)

**Other Required Information:**
 - OS: Ubuntu 18.04
 - Browser: Chrome
 - Version: 73

**Comment by chauhanparth210** [comment]
![Screenshot (3)](https://user-images.githubusercontent.com/35137224/54658160-0174fb80-4ac4-11e9-870b-6e9a37cfdc38.png)


@Diuda  please check the main site, it isn't a bug.
Thank you!!!

**Comment by sanyamdogra** [comment]
Hey @chauhanparth210, Please have a look at the `README.md`. New codebase resides in `next` branch. The website you are looking at is an older version. It is a bug in the newer one. Thanks
