### ISSUE TITLE
Popover position wrong in Popover -> Esempi interattivi

### ISSUE THREAD

**Issue by Diuda** [italia/design-react-kit#134]
**Describe the bug**
Popover in `Popover` component's `Esempi interattivi` tab does not come to left when the left position is selected from knobs. Instead, it comes to right of Popover button

**To Reproduce**
1. Go to `Popover` Component.
2. Click on `Esempi interattivi` tab.
3. Select _left_ position from knobs.
4. Notice that popover appears on right instead of left.

**Expected behavior**
The popover should appear on left when left position is selected from the knob.

**Screenshots**
Current State
![Screenshot from 2019-03-22 18-39-18](https://user-images.githubusercontent.com/12708871/54824773-e8419a00-4cd1-11e9-9151-84b7c6b58cde.png)

**Other Required Information (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Chrome
 - Version: 73

**Additional context**
As far as I dug into this issue the component `<Popover>` from _reactstrap_ is broken.
According to their [official website](https://reactstrap.github.io/components/popovers/), the popover component in **Popover Placements** section also has this issue.
When you click on left button, the popover opens on right.

**Comment by sanyamdogra** [comment]
This is probably happening because there is no space on the left to show the popup. Let me make a PR for the Fix.

**Comment by Diuda** [comment]
PR #137 has a good workaround but I guess it's just the issue with reactstrap `Popover` component. The [link](https://reactstrap.github.io/components/popovers/) has the same issue and _attributes_ like **data-placement** and **x-placement** do not change and remain as `right`. Not sure how they are maintaining those classes and attributes.

**Comment by sanyamdogra** [comment]
Yes it might be the case but popover should adapt itself according to the available space. So it's not exactly a bug.

**Comment by Diuda** [comment]
Yeah, that's right. Still not sure how props are being handled for the div of `popover` according to available space. The right and left **data-placement** and **x-placement** changes according to that.
