### ISSUE TITLE
Lables in Select component should be above the select bar not below

### ISSUE THREAD

**Issue by RMCoder198** [italia/design-react-kit#138]
**Describe the bug**
Lables in select component are below the select bar,lables should be above the select bar

**To Reproduce**
1. Go to select component
2. See error

**Expected behavior**
![000000](https://user-images.githubusercontent.com/26675957/54883791-8c247480-4e8f-11e9-9f98-4be633a23c82.png)

**Current behavior**
![000](https://user-images.githubusercontent.com/26675957/54883794-9181bf00-4e8f-11e9-9bfd-ef71a9e32ebb.png)

**Other Required Information (please complete the following information):**
 - OS: [ubuntu]
 - Browser [chrome]

**Comment by sanyamdogra** [comment]
Please do have a look at the current PRs before making an issue. Already fixed in #132, Thanks

**Comment by sanyamdogra** [comment]
You may close it.

**Comment by RMCoder198** [comment]
@sanyamdogra  sorry bro

**Comment by RMCoder198** [comment]
@sanyamdogra  It would be better if you first create an issue then send a PR even if it's a very minor change

**Comment by sanyamdogra** [comment]
Issue for select component was already made by a another contributor. It was just an addition to it.

**Comment by RMCoder198** [comment]
@sanyamdogra  Yeah but he didn't solve it correctly so i only checked his pull request that was already merged.
