### ISSUE TITLE
[BUG] "Input group" examples should be placed in the "Form" folder

### ISSUE THREAD

**Issue by francescozaia** [italia/design-react-kit#150]
**Describe the bug**
 [Input group](https://design-react-kit.netlify.com/?path=/story/componenti-input-group--esempi) examples should be simplified accordingly to [Bootstrap Italia](https://italia.github.io/bootstrap-italia/docs/form/input/):
- some examples have to be removed and the examples should be placed inside the 'Input' component
- everything should be placed inside the 'Form' folder 

**Expected behavior**
The 'Input group' should be placed inside 'Form' folder and refactored according to [Bootstrap Italia](https://italia.github.io/bootstrap-italia/docs/form/input/).

**Comment by Diuda** [comment]
All these different features mentioned [here](https://italia.github.io/bootstrap-italia/docs/form/input/) can be modeled into a single component and other redundant components can be removed.

I'll be happy to pick this up
