### ISSUE TITLE
[BUG] 'ScrollSpy' component should be renamed to 'NavScroll'

### ISSUE THREAD

**Issue by francescozaia** [italia/design-react-kit#153]
**Describe the bug**
'ScrollSpy' component correspond to what now is [Bootstrap Italia NavScroll](https://italia.github.io/bootstrap-italia/docs/menu-di-navigazione/navscroll/) and should be refactored accordingly.

**Expected behavior**
Refactoring should involve:
- Amending styling according to Bootstrap Italia
- Making it working for every screen size
- Update `react-scrollspy` to the latest version if needed, or remove it.

**Comment by Diuda** [comment]
Picking this up
