### ISSUE TITLE
[BUG] 'Card' component has to be updated

### ISSUE THREAD

**Issue by francescozaia** [italia/design-react-kit#154]
**Describe the bug**
'Card' component is out-of-date.

**To Reproduce**
1. Go to 'Card' > 'Esempi"
2. Compare it to ['Bootstrap Italia Card' component](https://italia.github.io/bootstrap-italia/docs/componenti/card/)
3. See error

**Expected behavior**
It should behave accordingly to Bootstrap Italia component.

**Comment by sanyamdogra** [comment]
@francescozaia Working on this.
