### ISSUE TITLE
[BUG] 'Progress' component has to be updated and renamed

### ISSUE THREAD

**Issue by francescozaia** [italia/design-react-kit#155]
**Describe the bug**
'Progress' component is out-of-date.

**To Reproduce**
1. Go to 'Progress' > 'Esempi"
2. Compare it to ['Bootstrap Italia Progress' component](https://italia.github.io/bootstrap-italia/docs/componenti/progress-indicators/)
3. See error

**Expected behavior**
It should behave accordingly to Bootstrap Italia component, and renamed to "Progress Indicators"

**Comment by sanyamdogra** [comment]
I would like to give it a shot!

**Comment by Diuda** [comment]
> I would like to give it a shot!

Hey, I already changed the code according to Bootstrap Italia and opened a PR. You can work on some other issue meanwhile if that's okay with you

**Comment by sanyamdogra** [comment]
@Diuda it's okay, next time please claim an issue before pushing a PR.

**Comment by francescozaia** [comment]
Thanks guys, we'll check the PR ASAP.

**Comment by sanyamdogra** [comment]
Opening it again as many implementatios of  Progress component is not yet completed.

**Comment by francescozaia** [comment]
Correct @sanyamdogra thanks.
