### ISSUE TITLE
[FEATURE] Update to the most recent version of ReactStrap

### ISSUE THREAD

**Issue by francescozaia** [italia/design-react-kit#174]
**Is your feature request related to a problem? Please describe.**
We're still using ReactStrap 7.x.

**Describe the solution you'd like**
Update to v 8.0 and verify any component that may have been broken in the process. Refer to [ReactStrap changeset](https://github.com/reactstrap/reactstrap/releases/tag/8.0.0) to see the changes.

**Comment by sanyamdogra** [comment]
Regarding the list of exports(Components) that were broken/not found in newer reactstrap are:- 
- CardBlock
- InputGroupButtonNavDropdown
- PopoverContent
- PopoverTitle
- UncontrolledNavDropdown
