### ISSUE TITLE
[BUG] 'Autocomplete' component is not styled properly and it is showcased twice

### ISSUE THREAD

**Issue by francescozaia** [italia/design-react-kit#178]
**Describe the bug**
Fix any styling issues with the "Input Autocomplete" component. Guessing the HTML generated from React is not correct, it should just work by applying Bootstrap Italia CSS.

We are also showing **two** "Input autocomplete" implementations:

- one on the main menu
- one can be found inside "Form" folder

Choose which one we prefer to keep and move/keep it inside "Form" folder, and  remove any unnecessary code.

**Expected behavior**
Please refer to Bootstrap Italia "autocomplete with data" example: https://italia.github.io/bootstrap-italia/docs/form/input/#autocompletamento-con-dati

![BI-input-autocomplete](https://user-images.githubusercontent.com/481084/58160140-29c4d600-7c7e-11e9-98d9-5b1ca574c2c1.png)

**Comment by sanyamdogra** [comment]
@francescozaia It was a WIP 🙅. Okay to merge the PR but reopening this issue until we style and add api call.

**Comment by francescozaia** [comment]
Closing this as it works. Will descope the API call to a separate issue
