### ISSUE TITLE
[BUG] 'Toggles' component is showcased twice

### ISSUE THREAD

**Issue by francescozaia** [italia/design-react-kit#180]
**Describe the bug**
We are showing **two** "Input autocomplete" implementations:

- one on the main menu
- one can be found inside "Form" folder

**Expected behavior**
Choose which one we prefer to keep and move/keep it inside "Form" folder, and  remove any unnecessary code.
Also, fix any styling issues with the component, if present. Please refer to Bootstrap Italia "Input autocomplete" example: https://italia.github.io/bootstrap-italia/docs/form/input/#autocompletamento-con-dati

**Comment by sanyamdogra** [comment]
@francescozaia I think this is duplicate of #178 ?

**Comment by francescozaia** [comment]
Don't what happened with these two issues, closing this for now.
