### ISSUE TITLE
[FEATURE] Use stackBlitz to expose the library

### ISSUE THREAD

**Issue by francescozaia** [italia/design-react-kit#185]
**Is your feature request related to a problem? Please describe.**
In a similar way to [what I've done ages ago](https://stackblitz.com/edit/react-bootstrap-italia)*, please create a StackBlitz (or an equivalent tool) _App_ to display:

- A short text with Tooltips
- A couple of different variants of buttons

*_note that fonts are not rendered properly due to a change on Bootstrap Italia_

**Comment by Hemant27031999** [comment]
Hi @francescozaia ,
Is this issue still open?
Thanks.
