### ISSUE TITLE
Define a testing strategy

### ISSUE THREAD

**Issue by francescozaia** [italia/design-react-kit#23]
Let's set up a testing suite to find bugs and make sure things won’t break between new code commits. We should have in place:
- CSS/Style Testing to ensure consistency with the [Design UI Kit](https://github.com/italia/design-ui-kit)
- Structural Testing to validate composition between components

Read "Testing" pages on Storybook docs, starting from https://storybook.js.org/testing/react-ui-testing/.

This issue is complete with:
- a [Snapshot](https://storybook.js.org/docs/testing/structural-testing/) test
- an [Interaction](https://storybook.js.org/docs/testing/interaction-testing/) test

**Comment by dej611** [comment]
Snapshot testing potrebbe essere un buon inizio.
Se si riuscisse ad aggiungere BackstopJS sarebbe fantastico.

**Comment by mjhost** [comment]
mi sono trovato bene anche ad aggiungere una jest spy sul console error verificando che non venga chiamato.
`
const spy = jest.spyOn(global.console, 'error');
// test di rendering
expect(spy).not.toHaveBeenCalled();
`

**Comment by gesposito** [comment]
L'attuale strategia è basata su
- [/Storyshots.test.js](https://github.com/italia/design-react-kit/blob/master/src/Storyshots.test.js)
- [src/StoryshotsImages.test.js](https://github.com/italia/design-react-kit/blob/master/src/StoryshotsImages.test.js)

Entrambi utilizzano [@storybook/addon-storyshots](https://github.com/storybooks/storybook/tree/master/addons/storyshots).
Mentre il primo abilita il Jest Snapshot Testing tramite Storybook, generando le relative [snapshot](https://github.com/search?utf8=%E2%9C%93&q=repo%3Aitalia%2Fdesign-react-kit+extension%3Astoryshot&type=Code&ref=advsearch&l=&l=), il secondo crea le [image snapshots](https://github.com/italia/design-react-kit/tree/master/src/__image_snapshots__) e le (image) diffs tra due run con output diversi per la visual regression.

**Comment by pranshuchittora** [comment]
Hi, I would like to work on this issue if it's currently an issue.

**Comment by dej611** [comment]
I test sembrano essere rotti anche su `master`. Sarebbe una buona idea aggiustarli.
In aggiunta si potrebbe mettere una Github action for eseguirli sulle PR.
