### ISSUE TITLE
[FEATURE] Avatar component

### ISSUE THREAD

**Issue by francescozaia** [italia/design-react-kit#358]
Add a new Avatar component, following design and CSS styling as shown in [Bootstrap Italia documentation page](https://italia.github.io/bootstrap-italia/docs/componenti/avatar/).

**Comment by devevignesh** [comment]
I would like to claim this

**Comment by devevignesh** [comment]
Hey @francescozaia, I need to create all types for Avatar component mentioned in [Bootstrap Italia page](https://italia.github.io/bootstrap-italia/docs/componenti/avatar/) right? For example: 
`src
    └── components
        └── Avatar
            ├── Avatar.js
            ├── AvatarText.js
            ├── AvatarIcon.js
             ├── AvatarImage.js`

**Comment by francescozaia** [comment]
Hey @devevignesh that would be awesome, yes!

**Comment by ankingcodes** [comment]
@devevignesh are you still working on this? If you're not I would like to carry this forward.

**Comment by francescozaia** [comment]
@ankingcodes are you still interested in this?

**Comment by ankingcodes** [comment]
@francescozaia yeah i'm interested. Will work on it this weekend :+1: !

**Comment by ankingcodes** [comment]
@francescozaia there are elements such as `svg, image, a, h4` used in various in the html of Avatar in bootstrap italia. Is it required to make separate components for each them or they can be used as is in the `avatar.storybook.js`

**Comment by ankingcodes** [comment]
@francescozaia  the Avatar Link example would look like 
```javascript
const AvatarLink = () => (
    <AvatarContainer>
        <AvatarIcon size="size-xl" href="#">
            <img src="https://randomuser.me/api/portraits/women/41.jpg" alt="Anna Barbieri"></img>
        </AvatarIcon>
        <AvatarIcon size="size-xl" type="avatar-red" link="#">
            <p aria-hidden="true">MR</p>
            <span class="sr-only">Mario Rossi</span>
        </AvatarIcon>
        <AvatarIcon size="size-xl">
        </AvatarIcon>
        <AvatarIcon size="size-xl">
          <Icon icon="it-search" />
        </AvatarIcon>
    </AvatarContainer>
)
```
However, we can notice that when we hover the components, the colour seems to change. How do we accomplish that? Is it taken care by bootstrap italia css module? 
Should I simply add on a link `href="#"`?
