### ISSUE TITLE
[BUG] Review the Collapse component

### ISSUE THREAD

**Issue by francescozaia** [italia/design-react-kit#360]
**Describe the bug**
The Collapse component needs review:
- The "Esempi" example is not working as expected
- ~"Gruppi di elementi richiudibili" and "Accordion" should be merged into one example~
- Differences between "Gruppi di elementi richiudibili" and "Accordion" should be documented as per [1](https://italia.github.io/bootstrap-italia/docs/componenti/collapse/#gruppi-di-elementi-richiudibili) vs [2](https://italia.github.io/bootstrap-italia/docs/componenti/collapse/#accordion)
- Animations works only when element is expanding.

Everything should work as shown in [Bootstrap Italia documentation](https://italia.github.io/bootstrap-italia/docs/componenti/collapse/)

**Comment by ankingcodes** [comment]
@francescozaia  I'm interested in this. Can you please clarify the following : 
- What's the problem exactly in the "Examples" example? Is it the scroll bar that appears on the button-click? 
- By merging of "Groups of resealable elements" and "Accordion", do you mean [this](https://italia.github.io/bootstrap-italia/docs/componenti/collapse/#collapse-e-accordion-innestati) ?

**Comment by francescozaia** [comment]
Hey @ankingcodes sure thing!

- Problem with the "Esempi" example is the button is not doing anything at the moment, it should trigger an expanding/collapsing element as shown on the [same component](https://italia.github.io/bootstrap-italia/docs/componenti/collapse/#come-funziona) on its "parent" library Bootstrap Italia*.
- Nevermind sorry that was just a leftover: "Groups of resealable elements" and "Accordion" are ok, nothing to be done there. I just removed the bullet from the to-do list.


*Bootstrap Italia is the jQuery-version of this React Kit, ie. exposes same components and behaviours.

**Comment by ankingcodes** [comment]
@francescozaia I have worked on this. And I have made the following changes: 
- In the "Esempi" example, I have made two buttons "Link con href" and "Buttone con data-target" as of ["parent"](https://italia.github.io/bootstrap-italia/docs/componenti/collapse/#come-funziona) library.
- I have solved the animation bug. Now, all components inside the Collapse component have an entering and exiting animation exactly like the parent library.
- I still don't understand what you mean by "Differences between "Gruppi di elementi richiudibili" and "Accordion" should be documented as per 1 vs 2". Please clarify further.

If the last point isn't a big issue, I shall submit a PR as soon as you approve.

**Comment by francescozaia** [comment]
Hey @ankingcodes that's great, thanks. Last point is not important, it's just a matter of documenting the component - that we can do on a different issue. Please proceed with the PR! 🎉
