### ISSUE TITLE
[FEATURE] Document the Icon component

### ISSUE THREAD

**Issue by francescozaia** [italia/design-react-kit#361]
The Icon component is already [present on the codebase](https://github.com/italia/design-react-kit/tree/master/src/components/Icon), but there's no documentation nor a story for it.
We should have on Storybook page similar to the one depicting the component on Bootstrap Italia:
https://italia.github.io/bootstrap-italia/docs/utilities/icone/

Note: English language is fine for documentation purposes.

**Comment by dej611** [comment]
I made a story for that for #356 now in #345 .

**Comment by Pratyush1197** [comment]
Hello I am working on this issue but I am getting 'net::ERR_INVALID_URL' when I am trying to display icon on browser. Is the sprite.svg not existing now?

**Comment by dej611** [comment]
Extracted the Icon stuff from `dev/headernav` branch and made a PR.
