### ISSUE TITLE
[FEATURE] Sticky header component

### ISSUE THREAD

**Issue by francescozaia** [italia/design-react-kit#364]
We'd like to give developers a "Sticky header" option to create websites that partially hide header when site is scrolled down.

This task is a bit tricky, as the best approach would probably require starting from the [Bootstrap Italia implementation](https://italia.github.io/bootstrap-italia/docs/menu-di-navigazione/header/#header-sticky) for DOM and CSS, and replace jQuery JS with code that is better suited for React.

Desired result - as implemented with Bootstrap Italia - is visible here:
https://italia.github.io/bootstrap-italia/docs/esempi/template-comuni-vuoto/

**Comment by shakti97** [comment]
Can I try it?
if yes, is I m free to use jquery with react?

**Comment by francescozaia** [comment]
> Can I try it?
> if yes, is I m free to use jquery with react?

Hi @shakti97 sure thing, but we're not including jQuery on this project as the aim is to replace it with pure JS and ReactJS code. So, jQuery 🙅‍♂ 😄

**Comment by shakti97** [comment]
okay will try it with pure Js and ReactJs

**Comment by dej611** [comment]
@shakti97 it is worth branching off #345 for this feature

**Comment by francescozaia** [comment]
Hey @shakti97 are you still working on this or can we reassign it?

**Comment by kindavishal** [comment]
Hey folks! :wave: 
Need any help here? I could help if someone could give me a kickstart with what needs to be done here, in a bit more detail :sparkles:

**Comment by ankingcodes** [comment]
@dej611 @francescozaia I will take this up. Please assign me :)

**Comment by ankingcodes** [comment]
@dej611 I believe we can use `withKnobs` to display the behavior. What are your views?

**Comment by dej611** [comment]
There are a couple of cases where `sticky` header is used:
* isolated header component with knobs
* templates such Homepage or others that require it
* template in #433 where the list title has to be sticky as well

**Comment by ankingcodes** [comment]
@dej611 I have implemented the sticky header example as follows :
```javascript
const StickyHeader = () => {
    const open = boolean('show', false)
    if(!open)
  return (
    <Headers sticky>
        <CompleteHeader/>
    </Headers>
  )
  else 
  return (
      <Headers>
          <CompleteHeader/>  
      </Headers>
  )
    
}
```
Also , I have used it in the Homepage template.
However, when I scroll the page downwards I don't see the same behavior as in https://italia.github.io/bootstrap-italia/docs/esempi/template-comuni-vuoto/

But while debugging, I found `console.log(classes) ` in `headers.js` to give
`it-header-wrapper it-header-sticky` . Do you have an idea why this might happen? 
Is it because of storybook?
