### ISSUE TITLE
[FEATURE] Cookiebar component

### ISSUE THREAD

**Issue by francescozaia** [italia/design-react-kit#365]
Replicate the Cookiebar component for use in React projects.

Design and behaviour reference is [Bootstrap Italia Cookiebar component](https://italia.github.io/bootstrap-italia/docs/componenti/cookiebar/) as usual. In short, Cookiebar is shown every time a `cookies_consent` cookie is not present on the client browser -  it sets that cookie to true when "ok" button is clicked. Current JS code can be seen here:
https://github.com/italia/bootstrap-italia/blob/master/src/js/plugins/cookiebar.js

Working example (built with Bootstrap Italia) here: https://italia.github.io/bootstrap-italia/docs/esempi/cookiebar/

**Comment by ankingcodes** [comment]
@francescozaia I would like to work on this !!

**Comment by ankingcodes** [comment]
@francescozaia will i have to make a CookieBar.stories.js file in the stories directory too?

**Comment by sanyamdogra** [comment]
Hey @ankingcodes, Yes you should create a `Cookiebar.stories.js` file for consuming the `CookieBar.js` component and displaying it in the Storybook components list. Thanks!
