### ISSUE TITLE
[FEATURE] Create a listing for Layout Components

### ISSUE THREAD

**Issue by sanyamdogra** [italia/design-react-kit#372]
**Is your feature request related to a problem? Please describe.**
Create a listing for Layout Components:
- Row
- Col
- Container

Something similar to [this](https://reactstrap.github.io/components/layout/).

**Comment by evelew** [comment]
I'll get this one :)

**Comment by francescozaia** [comment]
Hey @evelew I think @sanyamdogra is already working on it as it's assigned to him.

**Comment by evelew** [comment]
@francescozaia ops, sorry.

**Comment by sanyamdogra** [comment]
Re-opening this!

**Comment by AugustasV** [comment]
Could you describe more in details, how exactly this task should be completed?

**Comment by Pratyush1197** [comment]
Hello I want to work on this Please assign me

**Comment by francescozaia** [comment]
Already assigned to @sanyamdogra

**Comment by dej611** [comment]
@sanyamdogra are you still working on this?

**Comment by sanyamdogra** [comment]
Working on it @dej611

**Comment by sanyamdogra** [comment]
Hi @dej611, I will close this one once you merge #435. Thanks!
