### ISSUE TITLE
Icons not loading on browser

### ISSUE THREAD

**Issue by Pratyush1197** [italia/design-react-kit#379]
**Describe the bug**
Hello!! I am trying to use the icon component but when I open it in browser I see no icon on screen.
In console log I am getting error 'net::ERR_INVALID_URL'. Can someone please help me what is the error
Thank you

**Comment by dej611** [comment]
How are you using the Icon component? Can you post an example here?

**Comment by Pratyush1197** [comment]
` function App() {
  return (
    <Icon className="bg-light align-bottom" icon="it-check-circle" />
  );
}`

here is mu App.js component
Can you please tell me what is wrong in this?Thank you

**Comment by dej611** [comment]
Tried your code in here and it works: https://codesandbox.io/embed/silly-burnell-c0fvu

**Comment by Pratyush1197** [comment]
It is still not working. But I think I found the error which is related to browser compatibility. I will try to figure it out!!
