### ISSUE TITLE
[BUG] Missing color prop in the Chip component

### ISSUE THREAD

**Issue by dej611** [italia/design-react-kit#386]
Just realised that Chips component have also color classes: https://github.com/italia/bootstrap-italia/blob/e123ded4b957a46f4e2af81dc5b4e36f1c4324e6/src/scss/custom/_chips.scss#L165

Classes are as usual:

* `primary`
* `secondary`
* `success`
* `warning`
* `danger`
* `info`

Consider to have a new prop `color` as used in reactstrap components.

**Comment by dej611** [comment]
Realised this as in many templates (Homepage, Amministrazione, etc..) the `chip-primary` class is widely used.

**Comment by Pratyush1197** [comment]
Can I work on this issue?
