### ISSUE TITLE
[FEATURE] Better Buttons props for Icon scenario

### ISSUE THREAD

**Issue by dej611** [italia/design-react-kit#387]
Consider some component logic for Button Icon versions.

A button with an icon needs a classname to make the component aware of its content:

```jsx
<Button color="primary" size="lg" className="btn-icon">
   <Icon color='white'/> Icon Button Large
</Button>
```

 I think this can be improved with some prop logic, something like this perhaps?

```jsx
<Button color="primary" size="lg" icon>
   <Icon color='white'/> Icon Button Large
</Button>
```

Suggestions are welcome.

**Comment by ankingcodes** [comment]
@dej611 as far as I know, this could be possible if the Button Component was created from scratch. Since, it has been imported from Reactstrap, I'm not sure how we can modify the default props.
