### ISSUE TITLE
[BUG] LinkList component should provide a way to add a title component

### ISSUE THREAD

**Issue by dej611** [italia/design-react-kit#389]
In the current state the `LinkList` component creates a double DOM node structure when instanciated:

```jsx
<LinkList/>
```

creates the following HTML:

```html
<div class="link-list-wrapper">
  <ul class="link-list">
  </ul>
</div>
```

In some templates in between the two DOM nodes there is a title component (taken [from here](https://italia.github.io/design-comuni-prototipi/esempi/bootstrap-italia/template-novita-evento.html):
```
<div className="link-list-wrapper menu-link-list">
  <h3 className="no_toc">Indice della pagina</h3>
  <ul className="link-list">
  ...
  </ul>
</div>
```

It would be nice to provide a way to either compose or at least add a title to the list.

**Comment by Pratyush1197** [comment]
Hello I can work on this.Can you please provide the Hacktoberfest tag in this issue :)

**Comment by ankingcodes** [comment]
@dej611  since this issue hadn't been assigned to anyone, I have worked on this issue.
