### ISSUE TITLE
[BUG] The input component can be broken

### ISSUE THREAD

**Issue by dej611** [italia/design-react-kit#394]
The Input component is doing to much stuff.
Please restore it to [its original state](https://github.com/italia/design-react-kit/commit/4c4b69ef74ba49a2df5302e983b4adc7bf2d6369) and tweak it as few as possible.

[Edit] Fixed link

**Comment by ankingcodes** [comment]
@dej611 could you describe the bug ? And the link is broken, it leads to nowhere.

**Comment by dej611** [comment]
### The problem

The `Input` component handles too many cases, filling the DOM with a structure which is too big to easily control.

It currently has **3 flavours** of this structure:

```jsx
<div className={wrapperClass}>
          <Tag
            {...attributes}
            ref={innerRef}
            className={classes}
            id={this.props.id}
            onFocus={this.toggleFocusLabel}
            onBlur={e => this.toggleBlurLabel(e)}
            placeholder={this.props.placeholder}
            value={this.props.value}
          />
          <label htmlFor={this.props.id} className="active">
            {this.props.label}
          </label>
          <small className={infoTextClass}>{this.props.infoText}</small>
        </div>
```

compared to the original version:

```jsx
<Tag {...attributes} ref={innerRef} className={classes} />
```

This makes it very hard to handle custom scenarios like the star rating system [in this template](https://italia.github.io/design-comuni-prototipi/esempi/bootstrap-italia/template-novita-evento.html) for instance as many others because of all those `div`s and `label`s floating around it.

### What's next?

Next step here is to define a strategy to better handle different scenarios:
* custom styling as in BI by default
* some range of flexibility to customize the component by the developer
* as less possible custom `props` to be added from the original version

Some strategy ideas could be:
1) define some "scope specific" input components - i.e. `TextInput`, `RadioInput`, etc...
2) or define a practical way to handle multiple scenarios in an elegant way.

As reference `reactstrap` leaves more flexibility to the developer promoting composition (`Label` + `Input` + other tags) over configuration (many `props`).
