### ISSUE TITLE
[FEATURE] Carousel component

### ISSUE THREAD

**Issue by dej611** [italia/design-react-kit#395]
Need a carousel component based on this design reference: https://italia.github.io/bootstrap-italia/docs/componenti/carousel/

Note:
* no jQuery dependency allowed - so no OWL-derived libs have to be used
* Give a try to react-slick ?
* Some styling here is allowed
* the looks and feel must strictly comply with the reference - @francescozaia will review it

**Comment by Pratyush1197** [comment]
I want to work on this

**Comment by Pratyush1197** [comment]
So as we are not using owl carousel  is it still necessary to use the classes defined in the bootstrap italia documentation of carousal?

**Comment by dej611** [comment]
@francescozaia can answer this better than me

**Comment by francescozaia** [comment]
In this particular case, I would say that's not necessary to keep owl carousel classes as far as we manage to obtain the same behaviour and the component is kind of self contained. You might also see if some libraries like https://www.npmjs.com/package/react-responsive-carousel or https://www.npmjs.com/package/pure-react-carousel fits with our use case. I wouldn't suggest using ReactStrap carousel as it doesn't have all the features we need.
Also, we're trying to [evaluate other solutions than OwlCarousel from Bootstrap Italia](https://github.com/italia/bootstrap-italia/issues/376) as well, so those classes may change in the next future.

**Comment by dej611** [comment]
Potential libraries:
* https://www.npmjs.com/package/react-responsive-carousel
* https://www.npmjs.com/package/react-alice-carousel
* https://www.npmjs.com/package/@brainhubeu/react-carousel
* https://www.npmjs.com/package/react-slick
* https://www.npmjs.com/package/nuka-carousel

**Comment by dej611** [comment]
Proposed Slick carousel also in the BI issue as it has support for various frameworks.

**Comment by Anmol270900** [comment]
I want to work on this issue. Please confirm if I may.
Right now, I am trying to use react-slick (https://github.com/akiran/react-slick) for this purpose. 
Do tell if there's something I need to know while working on this feature.
Thank you.

**Comment by sanyamdogra** [comment]
Hi @Anmol270900, you may go ahead with this!

**Comment by dej611** [comment]
The Bootstrap Italia went for `swiperjs`. I guess it's now possible to migrate also this to swiper?
Luckily it offers a first-part support for React: https://swiperjs.com/react/

**Comment by dej611** [comment]
Currently blocked by `bootstrap-italia`

**Comment by dej611** [comment]
Bootstrap Italia 1.x introduced a new carousel which can be implemented, so this issue is unblocked now
