### ISSUE TITLE
Fix styles in Storybook Addons

### ISSUE THREAD

**Issue by gesposito** [italia/design-react-kit#42]
Attualmente il file [bootstrap-italia.min.css](https://italia.github.io/bootstrap-italia/dist/css/bootstrap-italia.min.css)
incluso in [/.storybook/manager-head.html](https://github.com/italia/design-react-kit/blob/master/.storybook/manager-head.html)
va a sovrascrivere anche la sezione `Addons`, risultando nella sovrascrittura degli stili.
Sezioni come i `Knobs` non visualizzano per esempio le `<input type="checkbox" />` (poichè `bootstrap-italia` le personalizza).
I `Knobs` sono utilizzati negli `Esempi interattivi`.

- Corretto
![screen shot 2018-05-24 at 16 49 48](https://user-images.githubusercontent.com/735227/40493248-915f855a-5f72-11e8-825f-0ec4292b9dff.png)
- Sbagliato
![screen shot 2018-05-24 at 16 49 34](https://user-images.githubusercontent.com/735227/40493250-9190c4a8-5f72-11e8-86ab-300436d8abfa.png)

**Comment by francescozaia** [comment]
Ecco, questa è una brutta cosa di Bootstrap Italia, grazie di averla evidenziata. Ci guardiamo il prima possibile.

**Comment by gesposito** [comment]
Risolta con la release [v0.9.1](https://github.com/italia/bootstrap-italia/releases/tag/v0.9.1).
