### ISSUE TITLE
[FEATURE] Make component support the cssModules prop as in reactstrap

### ISSUE THREAD

**Issue by dej611** [italia/design-react-kit#431]
**Is your feature request related to a problem? Please describe.**
`reactstrap` has a styling overwrite mechanism with a `cssModules` prop that lets the user handle scenarios where classes are either different (custom-compiled css framework) or not required (edge cases for some special component)

**Describe the solution you'd like**
Integrate together with the `classNames` mechanism also the `cssModules` one. Some components already have it (i.e. `Input`) but tohers don't.

**Describe alternatives you've considered**
No alternative

**Comment by ankingcodes** [comment]
@dej611  Okay, so we need to use `mapToCssModules` from the `reactstrap` library or do we need to create a separate one for this kit ?  
Also, do all components require this feature ? If not, let's list the components that require this. 
I'd like to work on it.

**Comment by ankingcodes** [comment]
@dej611 any update on this ?

**Comment by dej611** [comment]
First list of components (WIP):
* [ ] Accordion
* [ ] Avatar
* [ ] BottomNav
* [ ] Button
* [ ] Callout

**Comment by dej611** [comment]
> Okay, so we need to use mapToCssModules from the reactstrap library or do we need to create a separate one for this kit ?
If exported we can use it, otherwise we need to implement one internally.
> Also, do all components require this feature ? If not, let's list the components that require this.
Generally speaking, if a component is using a classname from BI, then it is required to have this feature.
