### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by blackwolf08** [italia/design-react-kit#460]
**Describe the bug**
Navbar <a> tags not showing due to NavBar bg color

**To Reproduce**
Current implementation not showing correctly behavior

**Expected behavior**
NavLinks should be visible

**Screenshots**
![error](https://user-images.githubusercontent.com/31814079/71537176-4b85ea00-293e-11ea-9bc9-e545e50da995.png)
![theek](https://user-images.githubusercontent.com/31814079/71537178-4cb71700-293e-11ea-91b9-925176c76ef3.png)

**Comment by blackwolf08** [comment]
@sanyamdogra @francescozaia

**Comment by sanyamdogra** [comment]
Hi @blackwolf08, Kindly refer to the comments in PR #461. Thanks
