### ISSUE TITLE
[BUG] Knobs panel seem to be broken in Firefox

### ISSUE THREAD

**Issue by dej611** [italia/design-react-kit#462]
**Describe the bug**

On each story a bottom panel for each page was available where parameters could have been changed with "knobs".
On newer version of Storybook configurations have changed, so probably during an update an unnoticed change broke this.

As reference this is the knobs addon page: https://www.learnstorybook.com/intro-to-storybook/react/en/using-addons/

**To Reproduce**
1. Open any new story page
2. See there's no panel at the bottom

**Comment by sanyamdogra** [comment]
Hi @dej611, Can you list out some specific examples? Thanks!

**Comment by dej611** [comment]
Ok, just realised that the panel is broken in Firefox. In Chrome it works fine.

**Comment by dej611** [comment]
See also #430 if interested in this issue.
