### ISSUE TITLE
[FEATURE] Make CardReadMore support the tag prop

### ISSUE THREAD

**Issue by dej611** [italia/design-react-kit#465]
CardReadMore wraps a link component. Many frameworks and/or libraries, like React Router or Next.js, usually provide their own link component to be used for the client-side routing.

The `NavLink`, as reference, supports the `tag` prop in a way that makes easier to integrate with other components.

**Comment by Hemant27031999** [comment]
@dej611 I would like to work on this issue.

**Comment by dej611** [comment]
Sure. You need more details?

**Comment by Hemant27031999** [comment]
@dej611 , I think what you want is something like this 
`<CardReadMore
              iconName="it-arrow-right"
              text="Leggi di più"
              tag={ Link }
              to={linkOption}
            />`
where the 'tag' prop takes in a html tag which you want to use for navigation like Link or NavLink and the 'to' prop is the path to the component on which we have to navigate.
Is it correct or do you want something else?

**Comment by dej611** [comment]
The `tag` prop can be a first start.
The `to` option... not so sure: `attributes` are already spread on the anchor component within `CardReadMore`, so there's no need to add an explicit `to`, I think.
