### ISSUE TITLE
[FEATURE] Dimmer component

### ISSUE THREAD

**Issue by dej611** [italia/design-react-kit#498]
**Describe the solution you'd like**
Create a Dimmer component based on the original Bootstrap Italia Dimmer component shape: https://italia.github.io/bootstrap-italia/docs/componenti/dimmer/

* [ ] Create style first
* [ ] Explain how to toggle it in the documentation
* [ ] Create a Storybook set of stories based on the BI documentation

*Notes*:
* use BI classes to style the component.
* no additional CSS is expected in this component, unless justified shortcomings of the original CSS.

**Comment by sanyamdogra** [comment]
Can I work on this?

**Comment by dej611** [comment]
sure
