### ISSUE TITLE
[FEATURE] Forward component

### ISSUE THREAD

**Issue by dej611** [italia/design-react-kit#499]
**Describe the solution you'd like**
Create a Forward component based on the original Bootstrap Italia Forward component:
https://italia.github.io/bootstrap-italia/docs/componenti/forward/

* [ ] Create the basic component
* [ ] Add the logic to scroll
* [ ] Create a Storybook set of stories based on the BI documentation

*Notes*:
* use BI classes to style the component.
* no additional CSS is expected in this component, unless justified shortcomings of the original CSS.

**Comment by ShreyansDubey** [comment]
Hello, I would like to work on this

**Comment by sanyamdogra** [comment]
Hi @ShreyansDubey, you may work on this.
