### ISSUE TITLE
[FEATURE] Complete Timeline component

### ISSUE THREAD

**Issue by dej611** [italia/design-react-kit#500]
**Describe the solution you'd like**
Verify and complete the Timeline component based on the original Bootstrap Italia Timeline component: https://italia.github.io/bootstrap-italia/docs/componenti/timeline/

* [ ] Verify the current state of the Timeline component
* [ ] Complete its implementation
* [ ] Add Storybook stories based on the BI documentation

*Notes*:
* use BI classes to style the component.
* no additional CSS is expected in this component, unless justified shortcomings of the original CSS.

**Comment by sanyamdogra** [comment]
On it!
