### ISSUE TITLE
[FEATURE] Steppers component

### ISSUE THREAD

**Issue by dej611** [italia/design-react-kit#501]
**Describe the solution you'd like**
Verify and complete the Steppers component based on the original Bootstrap Italia Steppers component: https://italia.github.io/bootstrap-italia/docs/componenti/steppers/

* [ ] Create the component
* [ ] Add Storybook stories based on the BI documentation

*Notes*:
* use BI classes to style the component.
* no additional CSS is expected in this component, unless justified shortcomings of the original CSS.

**Comment by ankingcodes** [comment]
I'd like to get this done 👍

**Comment by dej611** [comment]
Sure
