### ISSUE TITLE
[BUG] Visual Irregularity in Card component

### ISSUE THREAD

**Issue by sanyamdogra** [italia/design-react-kit#514]
**Describe the bug**
The Card component appears to be different from the one in BI.
[BI Ref](https://italia.github.io/bootstrap-italia/docs/componenti/card/)
**To Reproduce**
1. Go to live deployment.
2. Click on Cards > Simple Card
3. See the difference 

**Expected behavior**
![image](https://user-images.githubusercontent.com/33497630/74363132-f586dc00-4def-11ea-8c30-d8394b034020.png)

**Screenshots**
Current condition.
![image](https://user-images.githubusercontent.com/33497630/74363159-059ebb80-4df0-11ea-8883-280c0b906fbd.png)

**Additional context**

Probably, we are missing on some BI class or maybe due the usage of `<CardTitle>` from Reactstrap.

**Comment by ankingcodes** [comment]
In the `SimpleCard` story. I found that the `CardTitle` component was used from reactstrap. Using a 
`strong` tag such as :
```html
<CardTitle>
    <strong>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor…
    </strong>
</CardTitle>
```
gives the desired output. Should I make a PR for this ?

**Comment by sanyamdogra** [comment]
Hi @ankingcodes, that'll just make the heading bold and black. I think we should think of amending `CardTitle` to match up the styling of BI rather than using a `strong` tag because the aim is to provide ready-to-use components. But let's also consult @dej611.
Thanks!

**Comment by ankingcodes** [comment]
@sanyamdogra I checked out the CardTitle Component code on reactstrap, it uses a `Tag` where tag is a `div` whereas in BI a `h5` is used. Perhaps that's what's causing the issue. I suggest we create a new CardTitle component.

**Comment by dej611** [comment]
Maybe documentation here is enough than smart defaults: providing the example with the `tag='h5'` may suffice this time.

**Comment by ankingcodes** [comment]
@dej611 sure, I'll make a PR for this.

**Comment by sanyamdogra** [comment]
No Problem @ankingcodes, I made a PR as it was just a minor fix. You may work on completing #506, Cheers!
