### ISSUE TITLE
[FEATURE] Improve testing strategy

### ISSUE THREAD

**Issue by dej611** [italia/design-react-kit#516]
### Consistency testing

It would be nice, at least for static components, to test them against vanilla BI components HTML structure.

### Playground

It would be nice to have a playground where to experiment with components: something like a link, on each story, that opens the same code in a CodeSandbox or similar to help debugging or hack things together.

**Comment by ankingcodes** [comment]
Related to #185

**Comment by dej611** [comment]
Target branch for PRs: `migrate/storybook-6`
