### ISSUE TITLE
[FEATURE] Dropdown Component

### ISSUE THREAD

**Issue by ShreyansDubey** [italia/design-react-kit#517]
**Is your feature request related to a problem? Please describe.**
The current dropdown used is vanilla reactstrap without any changes, which uses a minium of three elements (Dropdown, DropdownToggle and DropdownMenu). These can be merged into a single component for ease of use.

**Describe the solution you'd like**
The existing structure can be changed like this,
```
<Dropdown>
  <DropdownToggle>
    <DropdownMenu>
      {props.children}
    </DropdownMenu>
  </DropdownToggle>
</Dropdown>
```
All of this will be one single component

The props that would need to be passed are [here](https://reactstrap.github.io/components/dropdowns/).
Most of the props have a default value so most of the time the user would only be dealing with only a few props. The only drawback I see here is that classnames need to be passed as props for each of the three elements. However, that should not be a big issue as BI dropdowns follow a specific style. If anyone wants to give custom styles, those classes can be passed as props but for most users this would not be the case.
Please add to this and/or comment on the feasibility of this.

**Comment by dej611** [comment]
I understand where this may come from, but I see some shortcomings:

* The assumption here is that those 3 components are always used in every dropdown scenario. But that's not necessary correct: for instance, the Drpopdown state sometimes is external (`Dropdown`) and sometimes is not (`UncontrolledDropdown`).

* Even with smarter default it needs some more thought about specific scenarios (for instance when a `Dropdown` is within a navbar or not), thus provide some props specific for this fourth component.

The problem I have is: what added value may provide this new component compared to the current setup?
I see the "less component" point, but to make a new component we ought to provide more than that, in my opinion at least.
