### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by shakti97** [italia/design-react-kit#528]
**Describe the bug**
Dropdown is transparent of Shortcut button (horizontal hamburger) in the sidebar 

**To Reproduce**
1. Go to 'https://italia.github.io/design-react-kit/?path=/story/componenti-badge--esempi'
2. Click on 'Circular hamburger shortcut button near the DESIGN REACT KIT in the sidebar'
3. You will see a transparent behaviour of the dropdown, which makes it looks weird and lose focus over the original dropdown text.

**Expected behavior**
The dropdown should be complete opaque so that one can see the content properly.

**Screenshots**
![Screenshot from 2020-02-18 22-39-28](https://user-images.githubusercontent.com/30585570/74761074-68390100-52a1-11ea-94cc-3fc9fe28c678.png)

**Other Required Information (please complete the following information):**
 - OS: Linux
 - Browser [chrome]
 - Version [80]

**Comment by shakti97** [comment]
if possible ,Would like to work on it

**Comment by sanyamdogra** [comment]
Hi @shakti97, thanks for raising an issue but I am afraid that that's an issue with the [storybook](https://github.com/storybookjs/) and not `design-react-kit`. You may file an issue with [storybook js](https://github.com/storybookjs/) if you like.

**Comment by shakti97** [comment]
okay
