### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by shakti97** [italia/design-react-kit#529]
**Is your feature request related to a problem? Please describe.**
When I close the sidebar by going to the shortcut button , there is no option for a user to open the sidebar again, if the user didn't know about the shortcut he need to reload the app.

**Describe the solution you'd like**
Giving a collapsible button on the left side which is visible when sidebar collapsed over the left edge.

**Comment by shakti97** [comment]
Would like to work on it

**Comment by sanyamdogra** [comment]
Please refer to - https://github.com/italia/design-react-kit/issues/528#issuecomment-587580372
Thanks!
