### ISSUE TITLE
Input fields e text areas non funzionano correttamente

### ISSUE THREAD

**Issue by francescozaia** [italia/design-react-kit#53]
Non è possibile visualizzare ciò che si scrive nei campi e la label non si sposta in alto per alcuni campi di input e text area, ad esempio [qui](https://italia.github.io/design-react-kit/?selectedKind=Componenti%2FForm&selectedStory=Input%20text&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel). Curiosamente, il secondo campo password in [questa pagina](https://italia.github.io/design-react-kit/?selectedKind=Componenti%2FForm&selectedStory=Input%20password&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs), funziona correttamente

**Comment by gesposito** [comment]
Per ottenere lo stesso effetto di `Bootstrap Italia` (realizzato con la classe `active` sul `form-group`) è stata implementata una versione custom del `FormGroup`.
Gli esempi vanno eventualmente aggiornati per utilizzare questo componente (wrappando le `Input`).

**Comment by gesposito** [comment]
Il `FormGroup` era già implementato ma erano stati migrati gli import degli `Input` (utilizzati per il children type check).
