### ISSUE TITLE
[DOC] Translate to italian all info boxes

### ISSUE THREAD

**Issue by dej611** [italia/design-react-kit#535]
**Describe the bug**
Some Info boxes have an english explanation on Storybook for components use.

**To Reproduce**
Open any Stepper story in Storybook and click on the Info panel: see the story in english rather than in italian.

**Expected behavior**
It would be nice to have all info panels coherent in Italian for now.

**Comment by fabriziofadigati** [comment]
Good afternoon,
I'm Fabrizio and it's my first time here.
I've just discovered Developers Italia and I would like to give my first official contribution by solving this translation issue.

**Comment by dej611** [comment]
Hi @fabriziofadigati, sure.
I think the best approach here is to pick some components in the `stories` folder and translate some `md` files.

**Comment by dej611** [comment]
Fixed by #631
