### ISSUE TITLE
[FEATURE] Toolbar component

### ISSUE THREAD

**Issue by dej611** [italia/design-react-kit#536]
### Describe the solution you'd like
Create a Toolbar component based on the original Bootstrap Italia Toolbar component:
https://italia.github.io/bootstrap-italia/docs/menu-di-navigazione/toolbar/

* [ ] Create the basic component
* [ ] Cover all the variants
* [ ] Create a Storybook set of stories based on the BI documentation

Notes:

* use BI classes to style the component.
* no additional CSS is expected in this component, unless justified shortcomings of the original CSS.

**Comment by ffranchina** [comment]
Hello, I've implemented the component and now I'm polishing the `.stories.js` file.
I have a question: how am I supposed to generate the `__snapshot__` folder and its content? I guess I should use some tools but I could not find in the readme anything about it.

**Comment by dej611** [comment]
```sh
yarn test
```
Then press <kbd>a</kbd>, then <kbd>u</kbd>.

**Comment by dej611** [comment]
Target branch for PRs: `migrate/storybook-6`

**Comment by dej611** [comment]
Fixed via #781 and #787
