### ISSUE TITLE
[FEATURE] Thumbnav component

### ISSUE THREAD

**Issue by dej611** [italia/design-react-kit#537]
### Describe the solution you'd like
Create a Thumbnav component based on the original Bootstrap Italia Thumbnav component: https://italia.github.io/bootstrap-italia/docs/menu-di-navigazione/thumbnav/

* [ ] Create the basic component
* [ ] Cover all the variants
* [ ] Create a Storybook set of stories based on the BI documentation

Notes:

* use BI classes to style the component.
* no additional CSS is expected in this component, unless justified shortcomings of the original CSS.

**Comment by dej611** [comment]
@ffranchina can you comment here so that I can assign this issue to you as well ( useful for the release )

**Comment by ffranchina** [comment]
Sure :)
