### ISSUE TITLE
[FEATURE] Plan to upgrade to Storybook 6

### ISSUE THREAD

**Issue by dej611** [italia/design-react-kit#545]
Storybook 6 is still in development, but it's getting close to the GA release.

We're still on Storybook 5.2, which can be upgraded to Storybook 5.3 with some simple version bumps, although a minor change has been introduced.

### The plan?

There's no particular rush to upgrade now, so it's worth planning a bit:
* the Storybook configuration can be revisited,
* there's already an issue to replace the `addon-info` with `addon-docs`,
*  introducing the new preset `create-react-app` is not trivial for our configuration (from some quick tests) - it is optional in 5.3 but will probably be mandatory for v. 6
* there's the opportunity to better plan structure of the documentation (feedback welcomed)

We could attempt to investigate an upgrade with a new `next-v6` branch. What do you think? @francescozaia @sanyamdogra 

### Quick tests

The `create-react-app` preset has been introduced since 5.3 as it is shown from the log below.

```sh
$ yarn start
yarn run v1.22.4
$ yarn run storybook:serve
$ start-storybook -p 9001 -c .storybook -s ./static
info @storybook/react v5.3.14
info 
info => Loading static files from: /design-react-kit/static .
info => Loading presets
info => Loading presets
WARN Storybook support for Create React App is now a separate preset.
WARN To get started with the new preset, simply add `@storybook/preset-create-react-app` to your project.
WARN The built-in preset will be disabled in Storybook 6.0.
WARN Storybook support for Create React App is now a separate preset.
WARN To get started with the new preset, simply add `@storybook/preset-create-react-app` to your project.
WARN The built-in preset will be disabled in Storybook 6.0.
info => Loading custom manager config.
info => Loading config/preview file in ".storybook".
WARN Storybook support for Create React App is now a separate preset.
WARN To get started with the new preset, simply add `@storybook/preset-create-react-app` to your project.
WARN The built-in preset will be disabled in Storybook 6.0.
info => Using default Webpack setup.
WARN Storybook support for Create React App is now a separate preset.
WARN To get started with the new preset, simply add `@storybook/preset-create-react-app` to your project.
WARN The built-in preset will be disabled in Storybook 6.0.
info => Loading create-react-app config.
```

A first attempt has been made with it but apparently newer versions have some constraints that go in conflicts with our configurations.
Maybe it is a good time to revisit such configuration?

**Comment by sanyamdogra** [comment]
Yes, we'll have to think about the `addon-docs` part. 
I went through their documentation and there's a way of migrating to MDX while keeping the `.stories.js` intact but this process is yet to explore.
* The addon-docs as mentioned by the documentation of Storybook, `.stories.mdx` will be the future. _We'll still have to discuss this part._
* Apart from this the file structure inside `.storybook/` has also changed.  
* Story export is much easier.
*  `storiesOf` will not be deprecated, most probably in ver 6 but they are pushing a new way to add stories by `ComponentName.story({...})`.

In totality, it'll be a major update.

Ref:
* https://github.com/storybookjs/storybook/blob/next/addons/docs/README.md#installation
* https://github.com/storybookjs/storybook/tree/next/addons/docs/react
* https://storybook.js.org/docs/formats/storiesof-api/

**Comment by dej611** [comment]
I had a first go with a local `next-6` branch, and these are my findings so far:

* there's some work to do in order to replace the `addon-info` with the `addon-docs`, but the result is quite convincing
* Some other `addons` may be refactored as well while in the process
* Stores can be ported with the new Storybook format with the [Codemod](https://github.com/storybookjs/storybook/blob/next/lib/core/docs/storiesOf.md#component-story-format-migration) which is much leaner to mantain
* There's no need for the `create-react-app` addon: it was a trick here to have a webpack config for free, but it's no longer required I think
* There's a nice addon to enable also `CodeSandbox` integration for examples #185 - see [this example](https://reaviz.io/?path=/docs/docs-chart-types-area-chart--page)

### The use of the `addon-doc`

Should we think about a new design for the documentation with this new tool?
What do you think @francescozaia ?

It is possible to replicate the BI documentation website with Reat components with this new `addon`:

<img width="1342" alt="Screenshot 2020-08-28 at 17 00 31" src="https://user-images.githubusercontent.com/924948/91582582-4c996c00-e950-11ea-97ed-5c417f5bcf90.png">
