### ISSUE TITLE
Il menù di selezione del componente Autocomplete non viene aperto al click

### ISSUE THREAD

**Issue by MassimilianoPia** [italia/design-react-kit#55]
Nella versione 2.2.0 quando viene cliccato il campo di input del componente Autocomplete il menù della select non viene aperto. Ho utilizzato lo stesso codice presente nell'esempio AutocompleteExample.

Allego il link alla sandbox: https://codesandbox.io/s/lrz28lxoyz

**Comment by gesposito** [comment]
Sono stati rilasciati aggiornamenti sia per `react-select` che per `bootstrap-italia`, al momento le versioni non sono lockate (quindi potrebbero ricevere breaking changes da versioni che rispettano lo stesso semver). C'è probabilmente da investigare in questo senso.

**Comment by gesposito** [comment]
E' stata pubblicata una nuova [minor](https://www.npmjs.com/package/design-react-kit/v/2.3.0) che aggiorna `react-select` alla `2.0.0`.

Ti ho aggiornato la sandbox, grazie per la segnalazione
https://codesandbox.io/s/pyw6oxkxym
