### ISSUE TITLE
La prop inputValue del componente Autocomplete non viene utilizzata

### ISSUE THREAD

**Issue by MassimilianoPia** [italia/design-react-kit#57]
Nella versione 2.2.0, nel componente Autocomplete non risulta possibile impostare il valore di input tramite la prop inputValue riportata in documentazione. 
Effettivamente all'interno del componente la prop non viene utilizzata ed è invece usato lo stato inputText inizializzato come una stringa vuota.
Non si può quindi inizializzare l'inputValue ad un valore di default (credo che comunque dovrebbe essere utilizzata la prop defaultInputValue di react-select, che però risulta inutilizzabile perchè sovrascritta dall'inputText di default).

Link alla sandbox: https://codesandbox.io/s/jnlx8vlvpy

**Comment by gesposito** [comment]
Viene utilizzato `inputText` dallo `state` per permettere una maggiore granularità della customizzazione necessaria in `Bootstrap Italia`. E' possibile ovviamente risolvere coi metodi lifecycle del componente.

**Comment by MassimilianoPia** [comment]
Grazie per la risposta tempestiva.
Ho provato ad impostare l'inputText di default facendo uso delle ref: https://codesandbox.io/s/vmry283kq7
Credo che sarebbe meglio rimuovere la prop inputValue del componente Autocomplete dalla documentazione se effettivamente non viene utilizzata, al fine di evitare di confondersi.

**Comment by gesposito** [comment]
E' stata pubblicata una nuova [patch](https://www.npmjs.com/package/design-react-kit/v/2.3.0) che rispetta la prop `defaultValue` di `react-select`.

Probabilmente come segnali dovremmo intervenire anche sulle [PropTypes](https://github.com/italia/design-react-kit/blob/master/src/components/Select/Select.js#L469) utilizzate dal componente per evitare che vengano esposte (se non ne permettiamo l'utilizzo).

Ti ho aggiornato la sandbox, grazie per la segnalazione
https://codesandbox.io/s/yqlp3jwo21
