### ISSUE TITLE
Error while run gatsby build

### ISSUE THREAD

**Issue by lmortellaro** [italia/design-react-kit#577]
Everything works fine when i run the develop script but when I run build this error occurs:

ERROR #95313

Building static HTML failed

See our docs page for more info on this error: https://gatsby.dev/debug-html

543 | className: PropTypes.string,
544 | scrollToRef: PropTypes.shape({

    545 | current: PropTypes.instanceOf(Element)
    | ^
    546 | })
    547 | };
    548 |

WebpackError: ReferenceError: Element is not defined

    design-react-kit.es.js:545
    node_modules/design-react-kit/dist/design-react-kit.es.js:545:23

    header.js:1
    src/components/header.js:1:1

    404.js:1
    src/pages/404.js:1:1

    sync-requires.js:8
    node_modules/$virtual/sync-requires.js:8:53

Changing line 545 from current: PropTypes.instanceOf(Element) to current: PropTypes.any I get no more errors but I'm not sure at all this is a proper solution.
Can you help me please?

**Comment by dej611** [comment]
Perhaps it is worth adding the Gatsby project to the CI checks? @francescozaia what do you think?
