### ISSUE TITLE
[BUG] Website is down

### ISSUE THREAD

**Issue by marcofugaro** [italia/design-react-kit#590]
**Describe the bug**
Website is currently broken, there are some errors in the console https://italia.github.io/design-react-kit/

**To Reproduce**
1. Go to https://italia.github.io/design-react-kit/
2. Is broken

**Expected behavior**
Works.

**Screenshots**
![image](https://user-images.githubusercontent.com/7217420/92374471-09818a80-f100-11ea-93dd-d937cc266103.png)

**Comment by francescozaia** [comment]
Should work better now, also updated few dependencies.

I guess it was a problem with CircleCI deploying Dependabot branches. We should amend CircleCI config file to deploy `master` branch only.

For now, I also disabled Dependabot automations.
