### ISSUE TITLE
[BUG] Navbar links are not visible in the stories

### ISSUE THREAD

**Issue by dej611** [italia/design-react-kit#624]
**Describe the bug**

Link color is not correctly picked up in the stories as shown in picture:

<img width="1182" alt="Screenshot 2020-10-28 at 09 31 04" src="https://user-images.githubusercontent.com/924948/97411336-6af3f780-1900-11eb-88d6-d26918330096.png">

**Additional context**
The problem is relative to a BI fork of a Bootstrap class in the `Collapsable` component.
Reactstrap uses the deefault Bootstrap class `navbar-collapse` when using the `<Collapse navbar>...</Collapse>` component in the navbar, while BI requires the `navbar-collapsable` for the same element (see (here)[https://italia.github.io/bootstrap-italia/docs/menu-di-navigazione/header/#versioni-disponibili] for refs).

To solve this issue it is requires to pass the correct `cssModules` to the `Collapse` component here to map `navbar-collapse` to `navbar-collapsable`.

**Comment by simonhoyos** [comment]
@dej611 I would like to help you with this one

**Comment by dej611** [comment]
@simonhoyos sure. Some hints are already in the issue.
Here's the documentation on how the module works: https://www.npmjs.com/package/map-to-css-modules

The `reactstrap` package used in `Collapse` has already the prop exposed.

**Comment by simonhoyos** [comment]
Great @dej611. I'll start working on this right away
