### ISSUE TITLE
Hide action logger for homepage

### ISSUE THREAD

**Issue by francescozaia** [italia/design-react-kit#63]
We would like to hide the *Storybook* "Action logger" area on the bottom for the [homepage](https://italia.github.io/design-react-kit/).

`showAddonPanel: false` might do the trick.

**Comment by algomaster99** [comment]
@francescozaia Setting `showAddonPanel` to a single story is not available with the current version of storybook i.e. `3.4.11`. To solve this issue, storybook must be updated to version `4.0.0` or later. This link is the solution to this issue: https://github.com/storybooks/storybook/tree/v4.0.0/addons/options#using-per-story-options.

**Comment by francescozaia** [comment]
We now have Storybook 5 on the`next` branch. You can also contribute there. Readme files will be updated soon accordingly.

**Comment by algomaster99** [comment]
@francescozaia I think this issue can be closed since the #82 fixes it :)
