### ISSUE TITLE
Fix :focus issue with Checkbox and Toggles

### ISSUE THREAD

**Issue by NicolaFerracin** [italia/design-react-kit#64]
## Current
Quando si clicca su una checkbox o un toggle, l'elemento rimane in stato 'focus' con relativo stile (bordo arancione). [GIF](https://gyazo.com/584c86c8cdde10e2eb3e30c354ea3d0b)

## Expected
Dopo il clic, la checkbox e il toggle dovrebbero perdere lo stato 'focus'.

**Comment by gesposito** [comment]
Ciao Nicola, non sono sicuro che il comportamento debba essere quello che descrivi, per probabili issues di accessibilità (navigazione tra le checkbox). Mi informo meglio e ti aggiorno.

**Comment by NicolaFerracin** [comment]
Ciao! Hai ragione, ho appena provato con delle checkbox native ed effettivamente rimangono in stato :focus dopo essere state attivate/disattivate. Per una qualche ragione mi era sembrato un comportamento strano e l'ho etichettato come bug. Chiudo la issue, scusa il "falso allarme".
