### ISSUE TITLE
[FEATURE] Support numeric Input custom formats (currency, percentage, ...)

### ISSUE THREAD

**Issue by dej611** [italia/design-react-kit#645]
**Describe the solution you'd like**
Extend the Input examples based on the original "numeric" Input Bootstrap Italia documentation:
https://italia.github.io/bootstrap-italia/docs/form/input-numerico/#valuta

* [ ] Extend the current `Input` component to handle specific styling
* [ ] Add currency + percentage stories/examples
* [ ] Match the `disabled` styling in the story/example
* [ ] Make it work for the resizing story/example

Notes:

* use BI classes to style the component.
* minimize the amount of extra CSS to style in this component ( possibly creating a set of reusable `react-select` styles objects reusable

**Comment by alammoiz** [comment]
I would love to do this task, Please assign it to me @dej611

**Comment by dej611** [comment]
Sure @alammoiz .
Please target the `migrate/storybook-6` branch.

**Comment by baldoalessandro** [comment]
Hello @dej611, it seems to me that this issue is still relevant (no currency or percentage in the SB deploy). If so, I can try to implement it

**Comment by dej611** [comment]
sure @baldoalessandro 👍
