### ISSUE TITLE
[BUG] Can't create link groups in the slim header

### ISSUE THREAD

**Issue by emilioSp** [italia/design-react-kit#688]
**Describe the bug**
With the components `LinkList` and `LinkListItem`, I was unable to recreate the slim header like in the screenshot
I think the problem is that is not possible to apply a class to the `<li>` element.

**Expected behavior**
Find a way to apply a delimiter class to the `<li>` element of the `LinkListItem` component

**Screenshots**
![image](https://user-images.githubusercontent.com/22614105/110759513-f9349e80-824d-11eb-917f-fd0b7817bca6.png)

**Comment by dej611** [comment]
Is this still valid for 4.0.0 @emilioSp ?

you can pass the `divider` propyl the item, and an additional `wrapperClassName` for the `li` wrapper element

**Comment by emilioSp** [comment]
Hi @dej611,
I think it is not valid anymore. I close it.
