### ISSUE TITLE
Missing /dist folder

### ISSUE THREAD

**Issue by NicolaFerracin** [italia/design-react-kit#69]
- installa il kit con `yarn add design-react-kit`
- importa un componente nell’App (.i.e. `import { Button } from 'design-react-kit'`)
- errore:
```
./src/App.js
Module not found: Can't resolve 'design-react-kit' in '[...]/test/src'
```

Probabile causa:
La cartella `/dist` dovrebbe essere generata ed inclusa nel pacchetto npm.

**Comment by gesposito** [comment]
Ciao Nicola, provo a creare un repo pulito per riprodurre e ti aggiorno.
Al momento è stato testato su https://github.com/teamdigitale/italia-messages-web

**Comment by gesposito** [comment]
Ok, ho visto ora che viene linkata dal `package.json`.

**Comment by gesposito** [comment]
E' stata ripristinata nella versione `2.1.0`, grazie per la segnalazione!

https://unpkg.com/design-react-kit@2.10.0/dist/
