### ISSUE TITLE
[BUG] Improve treeshake for Icon component

### ISSUE THREAD

**Issue by dej611** [italia/design-react-kit#694]
**Describe the bug**
When importing the `Icon` component in a project, ALL the SVG icons are imported in the final bundle, with no threeshake.

Here's a bundle analysis of an app using only 8 components from the kit:

<img width="302" alt="Screenshot 2021-03-23 at 08 00 11" src="https://user-images.githubusercontent.com/924948/112106368-de4b1e00-8bad-11eb-815b-9b8cdad8f7c7.png">

The project is using only a *single* icon, but importing all of them.

**Comment by leonardfactory** [comment]
The problem arises from [this import in the `Icon` component](https://github.com/italia/design-react-kit/blob/master/src/components/Icon/Icon.js#L4); moving to single imports would drastically reduce the bundle size. This solution has been used by many UI libraries by now, like:

- [Blueprint](https://github.com/palantir/blueprint/issues/2193)
- [FontAwesome](https://fontawesome.com/how-to-use/javascript-api/other/tree-shaking)
- [A post about icons tree shaking](https://kevinkreuzer.medium.com/how-to-build-your-own-tree-shakable-svg-icons-library-in-less-than-30-minutes-9f7a4a324d29)

This solution anyway would require developers in userland to import the icons statically, for example:

```ts
import { NoteIcon } from 'design-react-kit';
// or with deep imports, i.e. if webpack treeshaking is not available
import { NoteIcon } from 'design-react-kit/icons/note';
```

A solution right now - if using webpack - could be to resolve the Svg assets to a custom file, so users can specify only the icons they need. I didn't test this, but I'm providing it here as a base reference if someone wants to fiddle around.

```ts
module.exports = {
  //...
  resolve: {
    alias: {
      "design-react-kit/src/components/icon/assets$": path.resolve(__dirname, "./src/design-react-kit-icons.js")
    }
  }
};
```

```ts
// in design-react-kit-icons.js, specify used icons
export { default as SvgItArrowDownCircle } from 'design-react-kit/src/components/icon/assets/ItArrowDownCircle.js'
```

**Comment by dej611** [comment]
I see what you mean.

I wonder if integrating the `Icon` main component with the icons index file, having all the icons explicitly imported may make any difference rather than expose the whole iconset outside.

Something like:
```js
import {A} from './iconA'
import {B} from './iconB'
...


export const Icon = (props) => {
  ... logic here to pick only the requested icon
};
```

I suspect it won't work as the compiler may not statically analyze which icon specifically has been used, but maybe it's worth a try.
