### ISSUE TITLE
[BUG] HeaderToggler is not a11y compliant

### ISSUE THREAD

**Issue by emilioSp** [italia/design-react-kit#695]
**Describe the bug**
The component `HeaderToggler` is not accessible according to https://validator.w3.org/nu

**To Reproduce**

1. Use the component like in the following lines
```
<HeaderToggler>
      <Icon icon="it-expand" size="sm" color="primary" />
</HeaderToggler>
```

The output is:
```
<a aria-label="Toggle navigation" aria-expanded="false" type="" href="#" class="it-opener d-lg-none d-inline navbar-toggler"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" class="icon icon-primary icon-sm sm"><path d="M11.6 15.4L6 9.8l.7-.8 4.9 4.9L16.5 9l.7.8z"></path></svg></a>
```

**Expected behavior**
No error using the w3c tool

**Screenshots**
![image](https://user-images.githubusercontent.com/22614105/112184370-70c7dd80-8bff-11eb-9e5a-969689a3ba1d.png)

**Comment by dej611** [comment]
Verified that the BI one is different from the react kit one, will align to it.
I should probably add some static a11y test to the project.

**Comment by emilioSp** [comment]
We use pa11y on _developers italia_ and on the new site _cloud italia_

https://github.com/italia/developers.italia.it/blob/master/scripts/pa11y.sh

https://github.com/italia/cloud.italia.it-site/blob/main/pa11y.sh
https://github.com/italia/cloud.italia.it-site/blob/main/package.json#L14

It doesn't reveal all the issues, but could help and can easily integrate into a CI pipeline.
