### ISSUE TITLE
[BUG] Is Notification component missing from default export?

### ISSUE THREAD

**Issue by LoFrance** [italia/design-react-kit#703]
**Describe the bug**
I tried to use the `design-react-kit` `Notification` component but when I tried to import into my project I got an error, so I  have inspected the code and I noticed that `Notification` isn't exported from `index.js`.

**To Reproduce**
1. Install `design-react-kit` as dependecy
2. Import `Notification`
3 See error

**Comment by dej611** [comment]
Good catch. I did fix that for the next version of the kit, but forgot to backport it. Will send a PR about it.
