### ISSUE TITLE
Missing Select component

### ISSUE THREAD

**Issue by gianlu21** [italia/design-react-kit#711]
Hi,when i install design-react-kit, why SELECT  component is no longer available? 
How can i use the select component now ?

**Comment by dej611** [comment]
Hi @gianlu21 , the `Select` component was removed long time ago (~ 3 years ago) and recently it has been added back to the kit via #707 .

In the next release it will be available.
Meanwhile you can see at the source code implementation to use it in your project importing `react-select`: https://github.com/italia/design-react-kit/blob/master/src/components/Select/Select.js
