### ISSUE TITLE
[FEATURE] Add linter for mdx file type

### ISSUE THREAD

**Issue by sanyamdogra** [italia/design-react-kit#715]
**Is your feature request related to a problem? Please describe.**

The ongoing migration to the new storybook stories deals with MDX file type. It would be better to have a linter in place to avoid discrepancies.

**Describe the solution you'd like**

The following linter should be fine to use. 
- https://github.com/mdx-js/eslint-mdx

**Additional context**

A better option can be considered too.

**Comment by dej611** [comment]
Fixed by #631
