### ISSUE TITLE
[FEATURE] Sezione Organizzare i contenuti

### ISSUE THREAD

**Issue by dej611** [italia/design-react-kit#721]
Completare documentazione:

* [x] Organizzare gli spazi - Griglie
* [x] Organizzare contenuti - Liste
* [ ] Organizzare contenuti - Liste di immagini
* [ ] Organizzare contenuti - Tabelle
* [ ] Organizzare contenuti - Tipografia

~~Target branch for PRs: `migrate/storybook-6`~~
`master` is now the target branch.

**Comment by mrkrash** [comment]
Hi, I have almost done, but I have two problem left:
- I don't know how to add code snippet of https://italia.github.io/bootstrap-italia/docs/organizzare-i-contenuti/tipografia/#tipografia-responsive. The compilation failed for the : character;
- even if I have no errors, the canvas don't show code. There is only a text with "No code available"
Can you help me?

**Comment by dej611** [comment]
Do you have a PR/branch av available to check?

**Comment by mrkrash** [comment]
Yes, I have a branch: [feature-721](https://github.com/mrkrash/design-react-kit/tree/feature-721)

**Comment by dej611** [comment]
> I don't know how to add code snippet of italia.github.io/bootstrap-italia/docs/organizzare-i-contenuti/tipografia/#tipografia-responsive. The compilation failed for the : character;

You can use the markdown notation of 3 ticks + language in the mdx:
```scss
html {
  font-size: 16px;
  @include media-breakpoint-up(sm) {
    font-size: 18px;
  }
}
```

> even if I have no errors, the canvas don't show code. There is only a text with "No code available"
Can you help me?

That is probably due to wrong id. You can find the id of the story from the URL, in this example the id is the part in the red box :
<img width="491" alt="Screenshot 2021-11-10 at 08 09 38" src="https://user-images.githubusercontent.com/924948/141066756-28cb1ad8-a1b4-4ec4-b01f-867ed6e14637.png">

If keep on encountering issues even with the right id, you can write the story inline:
```
<Canvas>
  <Story name='titillium-web'>
    <p className='text-sans-serif'>ABCDEFGHIJKLMNOPQRSTUVWXYZ</p>
    <p className='text-sans-serif'>abcdefghijklmnopqrstuvwxyz</p>
    <p className='text-sans-serif'>0123456789</p>
  </Story>
</Canvas>
```

Later on we could sort out how to move it in a separate file.
