### ISSUE TITLE
Remove `.no_toc` class from examples/components

### ISSUE THREAD

**Issue by dej611** [italia/design-react-kit#732]
**Describe the bug**

The `.no_toc` class is often used in examples or components in the kit, but the class is not an organic part of the BI kit: https://github.com/italia/bootstrap-italia/issues/495

This task aims to remove this useless class from this repo.

Target branch: `migrate/storybook-6`

**Comment by MukulKolpe** [comment]
Hey @dej611 can I work on this issue?

**Comment by dej611** [comment]
Sure. Mind to start from `migrate/storybook-6` branch and create a PR against that.

**Comment by MukulKolpe** [comment]
Doubt ->So I have to remove className='no_toc' from everywhere? or I have to use some other className

**Comment by dej611** [comment]
Just remove it from everywhere
