### ISSUE TITLE
Add husky pre commit hook to be lint staged to prevent merging bad formatted code

### ISSUE THREAD

**Issue by siddhant1** [italia/design-react-kit#74]

**Comment by siddhant1** [comment]
Sending in a Pull Request

**Comment by siddhant1** [comment]
@francescozaia would you like to look at it

**Comment by francescozaia** [comment]
Hey @siddhant1 we currently have [this command](https://github.com/italia/design-react-kit/blob/master/package.json#L38). If you feel that can be improved in any way, feel free to send a PR, thanks

**Comment by siddhant1** [comment]
I think the command just to a linting , I was thinking of adding a prettier config to pre-commit

**Comment by algomaster99** [comment]
@francescozaia Currently, the `.eslintrc` file doesn't contain any rules. Shall I write some rules which adhere to the current coding styles?

**Comment by siddhant1** [comment]
I think we should write rules for both eslint and prettier

**Comment by siddhant1** [comment]
@francescozaia can you provide one?
