### ISSUE TITLE
[BUG][Typings] Rating component should filter Input props

### ISSUE THREAD

**Issue by dej611** [italia/design-react-kit#763]
**Describe the bug**

The Rating typings is currently extending the `InputProps` ones, which carry some unused props for the component.

The unused props are:
* `bsSize` | `size` => check which one of the two is required for size
* `static` | `plaintext` | `normalized` | `addon`
* `placeholder` | `label` | `value` | `type`

**Comment by mendaomn** [comment]
Sure, will put something together tomorrow!
