### ISSUE TITLE
The "Select" component cannot be imported

### ISSUE THREAD

**Issue by thewildboar** [italia/design-react-kit#771]
When I try to use the component describer here (https://italia.github.io/design-react-kit/?path=/docs/componenti-form-select--select-classica), I get this kind of error:

--> Attempted import error: 'Select' is not exported from 'design-react-kit'.

**To Reproduce**
1. import { Select } from 'design-react-kit';
2. use element < Select />
3. Build the project

**Expected behavior**
I would expect this code to build correctly and visualize an empty Select component, ready to be used with desired attributes/parameters, as the one seen in Storybook.

**Screenshots**
![image](https://user-images.githubusercontent.com/4179963/138893572-38398d5e-2162-4dab-ab3c-ba10e52b0f5c.png)

**Other Required Information (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 95.0.4638.54
 - design-react-kit version: 3.3.3

**Comment by dej611** [comment]
Close this as with the 4.0.0 release the component will be available.
