### ISSUE TITLE
[BUG] Production build doesn't load fonts

### ISSUE THREAD

**Issue by federico-ntr** [italia/design-react-kit#782]
**Describe the bug**
When doing `yarn start` the font is loaded and displayed correctly, it isn't loaded when serving a production build. I tried serving from Spring Boot and using the npm package `serve` running `serve -s build`

**To Reproduce**
1. `yarn create react-app font-test`
2. Install fonts as stated in [readme](https://github.com/italia/design-react-kit#aggiungere-bootstrap-italia-ed-i-font)
3. Import css and fonts in App.js as stated in [readme](https://github.com/italia/design-react-kit#appjs)
4. Run `yarn build` and then `serve -s build` in a terminal and `yarn start` in another terminal
5. Open devtools in the production build tab and notice how fonts are not even requested

**Expected behavior**
The fonts are correctly requested and loaded.

**Screenshots**
Production build:
![image](https://user-images.githubusercontent.com/35468654/142414225-4de7969d-a056-470a-9012-762f3f1e4db9.png)
Dev build:
![image](https://user-images.githubusercontent.com/35468654/142414154-9599d955-ef13-415d-9aa8-84ae70f2eebe.png)

**Other Required Information (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome 95

**Additional context**
I think this is actually not strictly related to design-react-kit since it's reproducible without even installing the kit, but if it's not a bug of the kit something should be stated in the readme, or maybe I did not understand something.

**Comment by dej611** [comment]
Latest `create-react-app` versions add an `index.css` and `App.css` css rules with system fonts that override the bootstrap-italia ones. Commenting the `import "./index.css"` (in the `index.js` file) and `import "./App.css"` You can notice the tililium font being loaded:
<img width="559" alt="Screenshot 2021-11-18 at 16 54 23" src="https://user-images.githubusercontent.com/924948/142449799-756a8622-f82d-402f-8360-c83faebd96eb.png">

Perhaps instructions should be updated with that, but I wouldn't consider a bug of the kit or bootstrap-italia, the browser is loading what it has been told: load the fonts required from css.

**Comment by dej611** [comment]
Will close the issue as non-bug. In case I've misunderstood something, please re-open it.

**Comment by federico-ntr** [comment]
My bad, I don't even know why I left that import.
