### ISSUE TITLE
Missing Documentation: Component ResponsiveImage

### ISSUE THREAD

**Issue by mrkrash** [italia/design-react-kit#788]
With feature #780, I have added this new component, but unfortunately I haven't written the documentation

**Comment by Virtute90** [comment]
As in the comment https://github.com/italia/design-react-kit/issues/789#issuecomment-1722238019 this component is only used in image lists, is specific documentation required?

**Comment by astagi** [comment]
https://italia.github.io/design-react-kit/?path=/story/documentazione-organizzare-i-contenuti-liste-di-immagini--page
