### ISSUE TITLE
Missing Documentation: Components Grids

### ISSUE THREAD

**Issue by mrkrash** [italia/design-react-kit#789]
With feature #780, I have added the new components **Griditem**, **GridItemText**, **GridItemTextWrapper**, **GridList** and **GridRow**.
Unfortunately I haven't written the documentation

**Comment by Virtute90** [comment]
When checking the stories, these components are only used for **image lists**.

In the "Organizing Spaces" documentation, the **Container**, **Row**, **Col** components are used.

Is specific documentation needed for these components at this point?

**Comment by mrkrash** [comment]
I suppose not but I defer to your opinion

**Comment by astagi** [comment]
https://italia.github.io/design-react-kit/?path=/story/documentazione-organizzare-gli-spazi-griglie--page
