### ISSUE TITLE
[ON HOLD] Update Storybook

### ISSUE THREAD

**Issue by francescozaia** [italia/design-react-kit#79]
Update Storybook to v5 [as soon as it's out](https://github.com/storybooks/storybook/milestones).

This will bring down updates to babel, react, and many other things. [Migration steps](https://github.com/storybooks/storybook/blob/next/MIGRATION.md#from-version-41x-to-50x) may be helpful in the process.

Comment out any component that isn't working properly and create issues for anything that needs rework.

**Comment by siddhant1** [comment]
Will be looking out here , are you creating a separate branch for this?

**Comment by francescozaia** [comment]
Hey sure, each feature will have its own branch.

**Comment by francescozaia** [comment]
This has been done on the `next` branch.
