### ISSUE TITLE
[FEATURE] Create a dev sandbox for a new development branch

### ISSUE THREAD

**Issue by francescozaia** [italia/design-react-kit#80]
**Is your feature request related to a problem? Please describe.**
As we’re moving towards a major overhaul of *Design React Kit* in the next months, we should have a new default development branch (i.e. `next`) for our dev work and we should be able to deploy the *Storybook* on Netlify or similar, as we currently do for the `master` branch [using GitHub pages](https://italia.github.io/design-react-kit/).

**Describe the solution you'd like**
An automated deploy to Netlify or similar? Open to discuss.

**Describe alternatives you've considered**
Feel free to comment out the issue

**Comment by sanyamdogra** [comment]
@francescozaia Yes Netlify is good, just push the build to git and continuous deployment will do the rest.

**Comment by siddhant1** [comment]
I think netlify continuous integration will be a great step.
