### ISSUE TITLE
[FEATURE] Start building with the kit the school templates

### ISSUE THREAD

**Issue by dej611** [italia/design-react-kit#826]
**Is your feature request related to a problem? Please describe.**
Replicate the school templates with the kit, appending it below the `Kit Comuni` as `Kit Scuole`.

**Describe the solution you'd like**
* Start from the plain pages here: https://github.com/italia/design-scuole-pagine-statiche/tree/master/build
* Rewrite page by page the full kit

**Comment by PyGera** [comment]
@dej611 Have anybody worked on that? Is it still useful? 

I can do it
