### ISSUE TITLE
[FEATURE] Offer test-id prop to all components

### ISSUE THREAD

**Issue by dej611** [italia/design-react-kit#832]
**Is your feature request related to a problem? Please describe.**
This should simplify the testing task and make in general testing more resilient to UI changes

**Comment by sanyamdogra** [comment]
Hey, you want this to be mapped with `data-testId` ? Or it is a generic prop given by DRK.
@dej611

**Comment by dej611** [comment]
Yes. The idea is to provide a `data-testId` (or just a `testId`) prop that gets propagated to the wrapper DOM node of each component.
