### ISSUE TITLE
[BUG] Firefox browser let user type alphabetic characters in numeric input

### ISSUE THREAD

**Issue by epicariello** [italia/design-react-kit#857]
Using Firefox, Input type number field accepts alphabetic characters. Using Chrome, it works correctly. 

Following code accepts alphabetics characters in Firefox. 
<code>
() => {
  const [value, setValue] = useState('100');
  return (
    <Input
      type='number'
      label='Min, Max & Step'
      value={value}
      min={-2000}
      max={15000}
      step={500}
      onChange={(ev) => {
        setValue(ev.target.value);
      }}
    />
  );
}
</code>

![image](https://user-images.githubusercontent.com/5927820/171130816-7b33506d-aff1-47c7-b3d8-76b21a584ca1.png)

**Comment by dej611** [comment]
That is just the native browser behavior for the `input` tag: I can reproduce the same problem here https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number .

Unless quirks or bugs the kit won't bend the native browser behaviour. In case I misunderstood the issue and it's actually a bug please reopen.
