### ISSUE TITLE
[BUG][ACCESSIBILITA'] Impossibile inserire la property "alt" nei componenti con icone

### ISSUE THREAD

**Issue by lolgames2012** [italia/design-react-kit#860]
In tutti i componenti che renderizzano immagini e/o icon, come ad esempio "Icon" e "HeaderBrand" è impossibile inserire l'attributo "alt", rendendo qualsiasi applicazione che usa la libreria non compatibile con lo standard di accessibilità  WCAG2AA

**Comment by dej611** [comment]
Will try to have a look at this 👍

**Comment by dennybiasiolli** [comment]
@dej611 working on it 😉 
Do you prefer `alt` to be mandatory for `Icon` components or optional?

**Comment by dej611** [comment]
I think optional is fine.
I think a mandatory prop makes sense to higher level components who use icons with no explicit label.

**Comment by dennybiasiolli** [comment]
Ok thanks, I will add a `<title></title>` element to `src/Icon/assets/It*.tsx` components, in order to comply with the same accessibility rules
