### ISSUE TITLE
[BUG] Megamenu responsive sidebar

### ISSUE THREAD

**Issue by pierluigizagaria** [italia/design-react-kit#884]
**Describe the bug**
The megamenu responsive sidebar doesn't render properly. The expanded dropdown content overflows the other headings.

**To Reproduce**
Build a megamenu with more headings and trigger the responsive sidebar.

**Expected behavior**

**Screenshots*
<img width="915" alt="Schermata 2022-11-02 alle 15 17 37" src="https://user-images.githubusercontent.com/57801386/199531170-6d9a8803-86c4-4b0a-a537-b632129c84fd.png">

**Other Required Information (please complete the following information):**
 - OS: MacOS
 - Browser: Safari
 - Version: 16

**Comment by dej611** [comment]
Do you have a code snippet to reproduce the same layout? A codesandbox is perfect

**Comment by pierluigizagaria** [comment]
Here is the codesandbox https://8kxzoz.csb.app
