### ISSUE TITLE
Components require fixing 

### ISSUE THREAD

**Issue by sanyamdogra** [italia/design-react-kit#90]
**Describe the bug**
After updating storybook many components broke. Try fixing the components in the list.
Note :- This is in reference to branch `next` and not `master`.
**List of components**

**[1] Autocomplete**
Current Status
![image](https://user-images.githubusercontent.com/33497630/54205857-30f09a80-44fd-11e9-9858-f706a88780b2.png)
Expected Status
![image](https://user-images.githubusercontent.com/33497630/54206029-87f66f80-44fd-11e9-8324-ac4617a40c63.png)

**[2] Input file (Form)**
Current Status
![image](https://user-images.githubusercontent.com/33497630/54206754-f25bdf80-44fe-11e9-8afc-5e704e4028c4.png)
Expected Status
![storyshots-images-test-js-image-storyshots-componenti-form-input-file-1-snap](https://user-images.githubusercontent.com/33497630/54207298-e7ee1580-44ff-11e9-931a-66142b68c573.png)

**Additional Context**
I'll be adding more components

**Comment by haxzie** [comment]
May I work on this?

**Comment by sanyamdogra** [comment]
Hey @haxzie which component would you like to work on?

**Comment by haxzie** [comment]
I can start with the first one :smile:

**Comment by sanyamdogra** [comment]
@haxzie You may go on with it!
