### ISSUE TITLE
[FEATURE] Card component

### ISSUE THREAD

**Issue by astagi** [italia/design-react-kit#906]
**Describe the solution you'd like**

Create a Card component based on the original Bootstrap Italia Card component:
https://italia.github.io/bootstrap-italia/docs/componenti/card/

* [ ] Create the base component if it doesn't exist or make it compatible with the BI 2 version
* [ ] Cover all the variants
* [ ] Create a Storybook series based on the documentation or update it for BI 2

Notes:

* use BI classes to style the component.
* minimize the amount of extra CSS to style in this component

**Comment by federico-ntr** [comment]
I just noticed the special card in the docs is missing a `href` attribute, that is why it doesn't show the right cursor, not a bug. I'll just make some docs editing, also adding a href to #.
