### ISSUE TITLE
Offcanvas component broken

### ISSUE THREAD

**Issue by sanyamdogra** [italia/design-react-kit#91]
**Describe the bug**
Offcanvas component is broken and is not displaying.
Note :- This is in reference to branch `next` and not `master`.

**To Reproduce**
1. Click on 'Offcanvas' component
2. See error

**Expected behavior**
This is how it should look.
![image](https://user-images.githubusercontent.com/33497630/54208044-410a7900-4501-11e9-84fd-a8f668dc5c08.png)

**Comment by RMCoder198** [comment]
@sanyamdogra  are you still working on it?

**Comment by sanyamdogra** [comment]
Hey @RMCoder198, yes i am working on this.
