### ISSUE TITLE
[FEATURE] Component checkbox

### ISSUE THREAD

**Issue by astagi** [italia/design-react-kit#913]
**Describe the solution you'd like**

Create a Checkbox component based on the original Bootstrap Italia Checkbox component:
https://italia.github.io/bootstrap-italia/docs/form/checkbox/

* [ ] Create the basic component
* [ ] Cover all the variants
* [ ] Create a Storybook set of stories based on the BI documentation

Notes:

* use BI classes to style the component.
* minimize the amount of extra CSS to style in this component

**Comment by sabato-galasso** [comment]
Closed #980
