### ISSUE TITLE
Migrate codebase of  branch 'next' from storybook 3.4.2 to 5.0.0

### ISSUE THREAD

**Issue by RMCoder198** [italia/design-react-kit#93]
Codebase needs migration from storybook 3.4.2 to 5.0.0

**Comment by sanyamdogra** [comment]
Hey @RMCoder198, the codebase of branch `next` has already been updated. The components require fixing. Any specific reason for this issue?

**Comment by RMCoder198** [comment]
@sanyamdogra No only dependecies are updated. Codebase still need to update for example decorator `checkA11y` has been deprecated and renamed to `withA11y`  but we are still using `checkA11y`.

**Comment by francescozaia** [comment]
Most of the deps are updated. If you could please create issues for any dependency that needs upgrade and tag the issue with the `next` label, that would be great.

**Comment by sanyamdogra** [comment]
Hi @francescozaia, i will surely create an issue but i don't have the rights to add labels.

**Comment by francescozaia** [comment]
@sanyamdogra no worries about that then, I'll take care of them. Thanks!

**Comment by sanyamdogra** [comment]
Hey @RMCoder198, I have opened an issue #94 for this. Thanks for pointing it out, you may close this.
