### ISSUE TITLE
[BUG] SyntaxError: Unexpected token '<'

### ISSUE THREAD

**Issue by tommasocisternino** [italia/design-react-kit#939]
**Describe the bug**
This bug is related to issue #936 
After the tries described on #936 I have pointed the package to branch master like suggested to me on the Slack channel.
After rebuilding the docker image, the previous error is gone but the following one is now appearing
![image](https://user-images.githubusercontent.com/71891129/220370912-e097f927-f75e-4f8a-b376-b89a28f5381d.png)

**To Reproduce**
Update the NextJS version to 13.1.7
Update the React version to 18
Update the design-react-kit to 4.0.2 pointing the package on master
Visit the NextJS microservice URL

**Other Required Information (please complete the following information):**
OS: W10
Browser Chrome
Version 4.0.2

**Comment by alexma01** [comment]
HI,

can you check in your **package-lock.json/yarn.lock** which version of the **bootstrap-italia** library is pointing to?

**Comment by tommaso-cisternino** [comment]
My package.lock is poiting to "bootstrap-italia": "^1.4.3".

**Comment by Pemo11235** [comment]
We experienced a similar issue related first to #936 and then on #939.
Probably the issues derive from the fact that Next.js doesn't transpile internal `node_modules`.
We solve the issue  using this `next.config.js` :

```
npm i @zeit/next-source-maps next-compose-plugins  next-transpile-modules @svgr/webpack
---
const withSourceMaps = require('@zeit/next-source-maps')
const withPlugins = require('next-compose-plugins')
const withTM = require('next-transpile-modules')(['design-react-kit'])

/** @type {import('next').NextConfig} */
const nextConfig = withPlugins([withTM, withSourceMaps], {
  reactStrictMode: true,
  assetPrefix: '/',
  webpack: (config, options) => {
    config.module.rules.push({
      test: /\.svg$/,
      use: ['@svgr/webpack'],
    })
```

    return config
  },
})

module.exports = nextConfig
```

Probably there is a cleaner solution. 
Hope that help
