### ISSUE TITLE
[Codebase Update] checkA11y is deprecated

### ISSUE THREAD

**Issue by sanyamdogra** [italia/design-react-kit#94]
**Is your feature request related to a problem? Please describe.**
The codebase is `next` branch is using checkA11y instead of withA11y.

**Describe the solution you'd like**
Update the codebase and remove deprecated checkA11y decorator.

**Additional context**
You may visit this [link](https://github.com/storybooks/storybook/tree/master/addons/a11y) for help.

**Comment by RMCoder198** [comment]
@sanyamdogra I already created that migration issue to remove deprecated code. You don't need to create a new issue. Few other changes are also need to done, so we can work together to migrate complete codebase.

**Comment by RMCoder198** [comment]
#93

**Comment by sanyamdogra** [comment]
@RMCoder198 Please mention the deprecated dependency and open a separate issue for it. Your issue was not specific. Thanks

**Comment by RMCoder198** [comment]
@sanyamdogra Well then okay , i have already changed code in few components. So I hope you are not working in this issue.

**Comment by sanyamdogra** [comment]
@RMCoder198 You may work on it! No problem.
