### ISSUE TITLE
[FEATURE] Upgrade to React 18

### ISSUE THREAD

**Issue by sabato-galasso** [italia/design-react-kit#963]
**Is your feature request related to a problem? Please describe.**
upgrade to React 18 for new features and to avoid becoming obsolete

**Describe the solution you'd like**
Migrate all functions, classes and components to React 18

**Comment by federico-ntr** [comment]
I see there are already two branches linked to this issue, have you started working on this, already, @sabato-galasso?

**Comment by Nick87** [comment]
I am trying to update the dependencies that need updating after the `react` and `react-dom` version bump: it is no easy task :)

**Comment by Nick87** [comment]
I have somehow managed to have the dependencies working, but I keep having a syntax error during the build: i have the same error in the main branch as well, and it is:

![image](https://github.com/italia/design-react-kit/assets/1497044/88a3e017-d409-42c2-aa4d-3df9b6aa8549)

have you ever come across this error? It does not recognize the optional chaining operator.

**Comment by sabato-galasso** [comment]
> I have somehow managed to have the dependencies working, but I keep getting a syntax error during the build: i have the same error in the main branch as well:
you can rebase the branch and try again from the updated version.

**Comment by Nick87** [comment]
I have opened a pr which is still in draft (#1049): `npm i` and `yarn build` complete successfully but I have 1 failing test.

N.B. I had to override `react-stickup` react dependency due to conflicting peer dependencies: it requires `react >=16.3.0 <18.0.0` and it is already at its latest version available.
