### ISSUE TITLE
[BUG] Could not find a declaration file for module 'design-react-kit' when moduleResolution='bundler'

### ISSUE THREAD

**Issue by VvsGitH** [italia/design-react-kit#972]
**Describe the bug**
I receive this error from typescript whenever I import a component from this library.

```
Could not find a declaration file for module 'design-react-kit'. '{project}/node_modules/design-react-kit/dist/esm/index.js' implicitly has an 'any' type. There are types at '{project}/node_modules/design-react-kit/dist/types/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'design-react-kit' library may need to update its package.json or typings.
```

The error only occurs if "moduleResolution" is equal to "NodeNext" or "bundler" in tsconfig.json.

**To Reproduce**
1. in tsconfig.json set compilerOptions.moduleResolution = "NodeNext" (or "bundler")
2. in a .tsx file import { Button } from "design-react-kit"

**Possible solution**
I tried making some changes in this library's package.json and I've found a possible solution, though I'm not an expert in library-making.

I replaced these lines
```json
"module": "dist/esm/index.js",
"main": "./src/index.tsx",
"typings": "dist/types/index.d.ts",
"exports": {
  "require": "./dist/index.js",
  "import": "./dist/esm/index.js",
  "default": "./dist/esm/index.js"
},
```
with
```json
"main": "dist/index.js",
"module": "dist/esm/index.js",
"typings": "dist/types/index.d.ts",
```
and everything seams to works just fine, even for moduleResolution="bundler".
This seams to be the default configuration of TSDX, so the handling of both esm and cjs should continue to work just fine.

**Other Required Information (please complete the following information):**
 - design-react-kit 4.0.2
 - typescript 5.0.2
 - vite 4.4.0

**Comment by Virtute90** [comment]
@astagi 

I'm starting a new project that includes design react kit and I was faced with this problem.

With moduleResolution="bundler" you need to change the package.json as reported by @VvsGitH otherwise the kit is not imported correctly.

Is moduleResolution="bundler" correct or do we need to set another one?
