### ISSUE TITLE
[BUG] [Next] The floating label does not work

### ISSUE THREAD

**Issue by Virtute90** [italia/design-react-kit#975]
**Describe the bug**
On focus the floating label doesn't work, am I doing something wrong?

**Expected behavior**
https://italia.github.io/bootstrap-italia/docs/form/input/

**Screenshots**
https://stackblitz.com/edit/stackblitz-starters-4zae7v?file=src%2FApp.tsx

**Comment by astagi** [comment]
Hi @Virtute90 yeah that was a problem we experienced in Bootstrap Italia (https://github.com/italia/design-angular-kit/issues/277). Update Bootstrap Italia to 2.7.8 and retry.
